Module kchem_kpp
 

!------------------------------------------------------------------------------!
! This file is part of PALM.
!
! PALM is free software: you can redistribute it and/or modify it under the
! terms of the GNU General Public License as published by the Free Software
! Foundation,either version 3 of the License,or (at your option) any later
! version.
!
! PALM is distributed in the hope that it will be useful,but WITHOUT ANY
! WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
! A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License along with
! PALM. If not,see <http://www.gnu.org/licenses/>.
!
! Copyright 1997-2016 Leibniz Universitaet Hannover
!------------------------------------------------------------------------------!


!  This module is automatically generated by kp4
!
!  Please do NOT change this Code
!

! Set kpp Double Precision to PALM Default Precision

  USE kinds,           ONLY: dp=>wp

  IMPLICIT        NONE
  PRIVATE
  !SAVE  ! NOTE: OCCURS AGAIN IN AUTOMATICALLY GENERATED CODE ...

!  PUBLIC :: IERR_NAMES
 
 ! PUBLIC :: SPC_NAMES,EQN_NAMES,EQN_TAGS,REQ_HET,REQ_AEROSOL,REQ_PHOTRAT &
 !         ,REQ_MCFCT,IP_MAX,jname

  PUBLIC :: EQN_NAMES,SPC_NAMES,NMAXFIXSTEPS
  PUBLIC :: atol,rtol
  PUBLIC :: NSPEC,nreact
  PUBLIC :: rconst
  PUBLIC :: NVAR
 
  PUBLIC :: Initialize,Integrate,Update_RCONST
  PUBLIC :: kpp_integrate
  PUBLIC :: initialize_kpp_ctrl

! END OF MODULE HEADER TEMPLATE
                                                                 
! Variables used for vector mode                                 
                                                                 
  logical,parameter           :: L_VECTOR=.FALSE.            
  integer,parameter           :: I_LU_DI = 0
  integer,parameter           :: VL_DIM=1
  integer                     :: vl                              
                                                                 
  integer                     :: VL_glo                          
  integer                     :: is,ie                           
                                                                 
  integer,dimension(VL_dim)   :: Kacc,Krej                       
  integer,dimension(VL_dim)   :: IERRV                           
  logical                     :: data_loaded=.false.             
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Parameter Module File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Parameters.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~






  !   NSPEC -  Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 16 
  !   NVAR -  Number of Variable species
  INTEGER, PARAMETER :: NVAR = 12 
  !   NVARACT -  Number of Active species
  INTEGER, PARAMETER :: NVARACT = 11 
  !   NFIX -  Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 4 
  !   NREACT -  Number of reactions
  INTEGER, PARAMETER :: NREACT = 12 
  !   NVARST -  Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
  !   NFIXST -  Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 13 
  !   NONZERO -  Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 53 
  !   LU_NONZERO -  Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 59 
  !   CNVAR -  (NVAR+ 1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 13 
  !   CNEQN -  (NREACT+ 1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 13 
  !   NHESS -  Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 28 
  !   NLOOKAT -  Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
  !   NMONITOR -  Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
  !   NMASS -  Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

  !   Index declaration for variable species in C and VAR
  !     VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER,PUBLIC :: ind_HNO3 = 1 
  INTEGER, PARAMETER,PUBLIC :: ind_O = 2 
  INTEGER, PARAMETER,PUBLIC :: ind_RH = 3 
  INTEGER, PARAMETER,PUBLIC :: ind_RCOO2NO2 = 4 
  INTEGER, PARAMETER,PUBLIC :: ind_O3 = 5 
  INTEGER, PARAMETER,PUBLIC :: ind_HO2 = 6 
  INTEGER, PARAMETER,PUBLIC :: ind_RCOO2 = 7 
  INTEGER, PARAMETER,PUBLIC :: ind_RCHO = 8 
  INTEGER, PARAMETER,PUBLIC :: ind_RO2 = 9 
  INTEGER, PARAMETER,PUBLIC :: ind_NO = 10 
  INTEGER, PARAMETER,PUBLIC :: ind_NO2 = 11 
  INTEGER, PARAMETER,PUBLIC :: ind_OH = 12 

  !   Index declaration for fixed species in C
  !     C(ind_spc)

  INTEGER, PARAMETER,PUBLIC :: ind_H2O = 13 
  INTEGER, PARAMETER,PUBLIC :: ind_O2 = 14 
  INTEGER, PARAMETER,PUBLIC :: ind_CO = 15 
  INTEGER, PARAMETER,PUBLIC :: ind_CO2 = 16 

  !   Index declaration for fixed species in FIX
  !      FIX(indf_spc) = C(ind_spc) = C(NVAR+ indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_CO = 3 
  INTEGER, PARAMETER :: indf_CO2 = 4 

  !   NJVRP -  Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 20 

  !   NSTOICM -  Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 39 


  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Global Data Module File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Global.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~






  !   Declaration of global variables

  !   C -  Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
  !   VAR -  Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
  !   FIX -  Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
  !   VAR, FIX are chunks of array C
      EQUIVALENCE( C(1),VAR(1))
      EQUIVALENCE( C(13),FIX(1))
  !   RCONST -  Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
  !   TIME -  Current integration time
  REAL(kind=dp) :: TIME
  !   SUN -  Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
  !   TEMP -  Temperature
  REAL(dp),dimension(:),allocatable             :: TEMP
  !   RTOLS -  (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
  !   TSTART -  Integration start time
  REAL(kind=dp) :: TSTART
  !   TEND -  Integration end time
  REAL(kind=dp) :: TEND
  !   DT -  Integration step
  REAL(kind=dp) :: DT
  !   ATOL -  Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
  !   RTOL -  Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
  !   STEPMIN -  Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
  !   STEPMAX -  Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
  !   CFACTOR -  Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR
  !   DDMTYPE -  DDM sensitivity w.r.t.: 0=init.val., 1=params
  INTEGER :: DDMTYPE

  !   INLINED global variable declarations

  !   INLINED global variable declarations



  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Sparse Jacobian Data Structures File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_JacobianSP.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~






  !   Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(59) :: LU_IROW =  (/ &
       1,  1,  1,  2,  2,  3,  3,  4,  4,  4,  5,  5, &
       5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7, &
       8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, &
      10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, &
      11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12 /) 

  INTEGER, PARAMETER, DIMENSION(59) :: LU_ICOL =  (/ &
       1, 11, 12,  2, 11,  3, 12,  4,  7, 11,  2,  5, &
      10, 11,  6,  8,  9, 10,  4,  7,  8, 10, 11, 12, &
       8,  9, 10, 12,  3,  7,  8,  9, 10, 11, 12,  5, &
       6,  7,  8,  9, 10, 11, 12,  4,  5,  6,  7,  8, &
       9, 10, 11, 12,  3,  6,  8,  9, 10, 11, 12 /) 

  INTEGER, PARAMETER, DIMENSION(13) :: LU_CROW =  (/ &
       1,  4,  6,  8, 11, 15, 19, 25, 29, 36, 44, 53, &
      60 /) 

  INTEGER, PARAMETER, DIMENSION(13) :: LU_DIAG =  (/ &
       1,  4,  6,  8, 12, 15, 20, 25, 32, 41, 51, 59, &
      60 /) 



  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Utility Data Module File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Monitor.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





  CHARACTER(LEN=15), PARAMETER, DIMENSION(16) :: SPC_NAMES =  (/ &
     'HNO3           ','O              ','RH             ',&
     'RCOO2NO2       ','O3             ','HO2            ',&
     'RCOO2          ','RCHO           ','RO2            ',&
     'NO             ','NO2            ','OH             ',&
     'H2O            ','O2             ','CO             ',&
     'CO2            ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(12) :: EQN_NAMES =  (/ &
     '        NO2 --> O + NO                                                                              ',&
     '     O + O2 --> O3                                                                                  ',&
     '    O3 + NO --> NO2 + O2                                                                            ',&
     '    RH + OH --> RO2 + H2O                                                                           ',&
     '  RCHO + OH --> RCOO2 + H2O                                                                         ',&
     '       RCHO --> HO2 + RO2 + CO                                                                      ',&
     '   HO2 + NO --> NO2 + OH                                                                            ',&
     '   RO2 + NO --> HO2 + RCHO + NO2                                                                    ',&
     ' RCOO2 + NO --> RO2 + NO2 + CO2                                                                     ',&
     '   NO2 + OH --> HNO3                                                                                ',&
     'RCOO2 + NO2 --> RCOO2NO2                                                                            ',&
     '   RCOO2NO2 --> RCOO2 + NO2                                                                         ' /)

  !   INLINED global variables

  !   End INLINED global variables


! Automatic generated PUBLIC Statements for ip_ and ihs_ variables 
 
! Automatic generated PUBLIC Statements for ip_ and ihs_ variables 
 
! Automatic generated PUBLIC Statements for ip_ and ihs_ variables 
 
! Automatic generated PUBLIC Statements for ip_ and ihs_ variables 
 
 
!  variable definations from  individual module headers 
 
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Initialization File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Initialize.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Numerical Integrator (Time-Stepping) File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Integrator.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   INTEGRATE -  Integrator routine
  !     Arguments :
  !        TIN       -  Start Time for Integration
  !        TOUT      -  End Time for Integration
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  !  
  !    Rosenbrock -  Implementation of several Rosenbrock methods:               !  
  !                 *Ros2                                                      !  
  !                 *Ros3                                                      !  
  !                 *Ros4                                                      !  
  !                 *Rodas3                                                    !  
  !                 *Rodas4                                                    !  
  !    By default the code employs the KPP sparse linear algebra routines       !  
  !    Compile with - DFULL_ALGEBRA to use full linear algebra (LAPACK)          !  
  !                                                                             !  
  !      (C)  Adrian Sandu, August 2004                                         !  
  !      Virginia Polytechnic Institute and State University                    !  
  !      Contact: sandu@cs.vt.edu                                               !  
  !      Revised by Philipp Miehe and Adrian Sandu, May 2006                    !                                   !  
  !      This implementation is part of KPP -  the Kinetic PreProcessor          !  
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  !  


  SAVE
  
  !  ~~~>  Statistics on the work performed by the Rosenbrock method
  INTEGER, PARAMETER :: Nfun=1, Njac=2, Nstp=3, Nacc=4, &
                        Nrej=5, Ndec=6, Nsol=7, Nsng=8, &
                        Ntexit=1, Nhexit=2, Nhnew = 3

  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Linear Algebra Data and Routines File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_LinearAlgebra.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~






  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   The ODE Jacobian of Chemical Model File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Jacobian.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~






  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   The ODE Function of Chemical Model File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Function.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





  !   A -  Rate for each equation
  REAL(kind=dp) :: A(NREACT)

  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   The Reaction Rates File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Rates.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   
  !   Auxiliary Routines File
  !   
  !   Generated by KPP- 2.2.3 symbolic chemistry Kinetics PreProcessor
  !         (http://www.cs.vt.edu/~asandu/Software/KPP)
  !   KPP is distributed under GPL, the general public licence
  !         (http://www.gnu.org/copyleft/gpl.html)
  !   (C) 1995- 1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
  !   (C) 1997- 2005, A. Sandu, Michigan Tech, Virginia Tech
  !       With important contributions from:
  !          M. Damian, Villanova University, USA
  !          R. Sander, Max- Planck Institute for Chemistry, Mainz, Germany
  !   
  !   File                 : kchem_kpp_Util.f90
  !   Time                 : Mon Mar  6 14:11:23 2017
  !   Working directory    : /pd/home/khan- b/palm/current_version/trunk/KPP_FOR_PALM/tmp_kp4
  !   Equation file        : kchem_kpp.kpp
  !   Output root filename : kchem_kpp
  !   
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~






   !  HEADER MODULE initialize_kpp_ctrl_template

   !  NOTES:
   !  -  L_VECTOR is automatically defined by kp4
   !  -  VL_DIM is automatically defined by kp4
   !  -  I_LU_DI is automatically defined by kp4
   !  -  WANTED is automatically defined by xmecca
   !  -  ICNTRL RCNTRL are automatically defined by kpp
   !  -  "USE messy_main_tools" is in Module_header of messy_mecca_kpp.f90
   !  -  SAVE will be automatically added by kp4

   ! SAVE

   !  FOR FIXED TIME STEP CONTROL
   !  ... max. number of fixed time steps (sum must be 1)
  INTEGER, PARAMETER         :: NMAXFIXSTEPS = 50
   !  ... switch for fixed time stepping
  LOGICAL, PUBLIC            :: l_fixed_step = .FALSE.
  INTEGER, PUBLIC            :: nfsteps = 1
   !  ... number of kpp control parameters
  INTEGER, PARAMETER, PUBLIC :: NKPPCTRL = 20
   ! 
  INTEGER,  DIMENSION(NKPPCTRL), PUBLIC     :: icntrl = 0
  REAL(DP), DIMENSION(NKPPCTRL), PUBLIC     :: rcntrl = 0.0_dp
  REAL(DP), DIMENSION(NMAXFIXSTEPS), PUBLIC :: t_steps = 0.0_dp

   !  END HEADER MODULE initialize_kpp_ctrl_template

 
! Interface Block 
 
  interface            Initialize
    module procedure   Initialize
  end interface        Initialize
 
  interface            INTEGRATE
    module procedure   INTEGRATE
  end interface        INTEGRATE
 
  interface            Fun
    module procedure   Fun
  end interface        Fun
 
  interface            KppSolve
    module procedure   KppSolve
  end interface        KppSolve
 
  interface            KppDecomp
    module procedure   KppDecomp
  end interface        KppDecomp
 
  interface            WLAMCH
    module procedure   WLAMCH
  end interface        WLAMCH
 
  interface            WLAMCH_ADD
    module procedure   WLAMCH_ADD
  end interface        WLAMCH_ADD
 
  interface            Jac_SP
    module procedure   Jac_SP
  end interface        Jac_SP
 
  interface            k_arr
    module procedure   k_arr
  end interface        k_arr
 
  interface            Update_RCONST
    module procedure   Update_RCONST
  end interface        Update_RCONST
 
  interface            k_3rd
    module procedure   k_3rd
  end interface        k_3rd
 
  interface            initialize_kpp_ctrl
    module procedure   initialize_kpp_ctrl
  end interface        initialize_kpp_ctrl
 
  interface            error_output
    module procedure   error_output
  end interface        error_output
 
!interface not working  interface            WCOPY
!interface not working    module procedure   WCOPY
!interface not working  end interface        WCOPY
 
  interface            WSCAL
    module procedure   WSCAL
  end interface        WSCAL
 
!interface not working  interface            WAXPY
!interface not working    module procedure   WAXPY
!interface not working  end interface        WAXPY
 
  interface            Rosenbrock
    module procedure   Rosenbrock
  end interface        Rosenbrock
 
  interface            FunTemplate
    module procedure   FunTemplate
  end interface        FunTemplate
 
  interface            JacTemplate
    module procedure   JacTemplate
  end interface        JacTemplate
 
  interface            Update_SUN
    module procedure   Update_SUN
  end interface        Update_SUN
 
  interface            kpp_integrate
    module procedure   kpp_integrate
  end interface        kpp_integrate
 
  interface            fill_TEMP
    module procedure   fill_TEMP
  end interface        fill_TEMP
  public               fill_TEMP
 
 
 CONTAINS
 
SUBROUTINE Initialize()
    IMPLICIT NONE               ! bK kkp1
  
  INTEGER :: i
  REAL(kind=dp) :: x

  CFACTOR = 1.000000e+00_dp

  x = (0.)*CFACTOR
  DO i = 1, NVAR
    VAR(i) = x
  END DO

  x = (0.)*CFACTOR
  DO i = 1, NFIX
    FIX(i) = x
  END DO

  !   constant rate coefficients
  RCONST(2) = 8.125e-19_dp      !bK
  RCONST(3) = 9.897e-13_dp      !bK
  RCONST(4) = 1.405e-10_dp      !bK
  RCONST(5) = 8.713e-10_dp      !bK
  RCONST(7) = 4.518e-10_dp      !bK
  RCONST(8) = 4.195e-10_dp      !bK
  RCONST(9) = 4.195e-10_dp      !bK
  RCONST(10) = 6.004e-10_dp     !bK
  RCONST(11) = 2.566e-10_dp     !bK
  RCONST(12) = 7.976e-16_dp     !bK
  


  !   END constant rate coefficients

  !   INLINED initializations

  !   End INLINED initializations

      
END SUBROUTINE Initialize
 
SUBROUTINE INTEGRATE( TIN, TOUT, &
  ICNTRL_U, RCNTRL_U, ISTATUS_U, RSTATUS_U, IERR_U)

    IMPLICIT NONE                                    ! bK kkp2
   REAL(kind=dp), INTENT(IN) :: TIN   !  Start Time
   REAL(kind=dp), INTENT(IN) :: TOUT  !  End Time
    !  Optional input parameters and statistics
   INTEGER,       INTENT(IN),  OPTIONAL :: ICNTRL_U(20)
   REAL(kind=dp), INTENT(IN),  OPTIONAL :: RCNTRL_U(20)
   INTEGER,       INTENT(OUT), OPTIONAL :: ISTATUS_U(20)
   REAL(kind=dp), INTENT(OUT), OPTIONAL :: RSTATUS_U(20)
   INTEGER,       INTENT(OUT), OPTIONAL :: IERR_U

   REAL(kind=dp) :: RCNTRL(20), RSTATUS(20)
   INTEGER       :: ICNTRL(20), ISTATUS(20), IERR

   INTEGER, SAVE :: Ntotal = 0

   ICNTRL(:)  = 0
   RCNTRL(:)  = 0.0_dp
   ISTATUS(:) = 0
   RSTATUS(:) = 0.0_dp

     ! ~~~> fine-tune the integrator:
   ICNTRL(1) = 0	 !  0 -  non- autonomous, 1 -  autonomous
   ICNTRL(2) = 0	 !  0 -  vector tolerances, 1 -  scalars

    !  If optional parameters are given, and if they are >0, 
    !  then they overwrite default settings. 
   IF (PRESENT(ICNTRL_U))THEN
     WHERE(ICNTRL_U(:) > 0) ICNTRL(:) = ICNTRL_U(:)
   END IF
   IF (PRESENT(RCNTRL_U))THEN
     WHERE(RCNTRL_U(:) > 0) RCNTRL(:) = RCNTRL_U(:)
   END IF


   CALL Rosenbrock(NVAR,VAR,TIN,TOUT,   &
         ATOL,RTOL,                &
         RCNTRL,ICNTRL,RSTATUS,ISTATUS,IERR)

    ! ~~~> Debug option: show no of steps
    !  Ntotal = Ntotal +  ISTATUS(Nstp)
   ! PRINT*,'NSTEPS=',ISTATUS(Nstp),' (',Ntotal,')','  O3=',VAR(ind_O3)

   STEPMIN = RSTATUS(Nhexit)
    !  if optional parameters are given for output they 
    !  are updated with the return information
   IF (PRESENT(ISTATUS_U))ISTATUS_U(:) = ISTATUS(:)
   IF (PRESENT(RSTATUS_U))RSTATUS_U(:) = RSTATUS(:)
   IF (PRESENT(IERR_U))   IERR_U       = IERR

END SUBROUTINE INTEGRATE
 
SUBROUTINE Fun(V, F, RCT, Vdot)
        IMPLICIT NONE               ! bK kkp3
  !   V -  Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
  !   F -  Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
  !   RCT -  Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
  !   Vdot -  Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


  !   Computation of equation rates
  A(1) = RCT(1)*V(11)           !bK
  A(2) = 8.125e-19_dp*V(2)*F(2)    !bK
  A(3) = 9.897e-13_dp*V(5)*V(10)   !bK
  A(4) = 1.405e-10_dp*V(3)*V(12)   !bK
  A(5) = 8.713e-10_dp*V(8)*V(12)   !bK
  A(6) = RCT(6)*V(8)            !bK
  A(7) = 4.518e-10_dp*V(6)*V(10)   !bK
  A(8) = 4.195e-10_dp*V(9)*V(10)   !bK
  A(9) = 4.195e-10_dp*V(7)*V(10)   !bK
  A(10) = 6.004e-10_dp*V(11)*V(12) !bK
  A(11) = 2.566e-10_dp*V(7)*V(11)  !bK
  A(12) = 7.976e-16_dp*V(4)        !bK

  !   Aggregate function
  Vdot(1) = A(10)
  Vdot(2) = A(1)- A(2)
  Vdot(3) = - A(4)
  Vdot(4) = A(11)- A(12)
  Vdot(5) = A(2)- A(3)
  Vdot(6) = A(6)- A(7)+ A(8)
  Vdot(7) = A(5)- A(9)- A(11)+ A(12)
  Vdot(8) = - A(5)- A(6)+ A(8)
  Vdot(9) = A(4)+ A(6)- A(8)+ A(9)
  Vdot(10) = A(1)- A(3)- A(7)- A(8)- A(9)
  Vdot(11) = - A(1)+ A(3)+ A(7)+ A(8)+ A(9)- A(10)- A(11)+ A(12)
  Vdot(12) = - A(4)- A(5)+ A(7)- A(10)
      
END SUBROUTINE Fun
 
SUBROUTINE KppSolve(JVS, X)
    IMPLICIT NONE                   ! bK kkp4
  !   JVS -  sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
  !   X -  Vector for variables
  REAL(kind=dp) :: X(NVAR)

  X(5) = X(5)- JVS(11)*X(2)
  X(7) = X(7)- JVS(19)*X(4)
  X(9) = X(9)- JVS(29)*X(3)- JVS(30)*X(7)- JVS(31)*X(8)
  X(10) = X(10)- JVS(36)*X(5)- JVS(37)*X(6)- JVS(38)*X(7)- JVS(39)*X(8)- JVS(40)*X(9)
  X(11) = X(11)- JVS(44)*X(4)- JVS(45)*X(5)- JVS(46)*X(6)- JVS(47)*X(7)- JVS(48)*X(8)- JVS(49)*X(9)- JVS(50)*X(10)
  X(12) = X(12)- JVS(53)*X(3)- JVS(54)*X(6)- JVS(55)*X(8)- JVS(56)*X(9)- JVS(57)*X(10)- JVS(58)*X(11)
  X(12) = X(12)/ JVS(59)
  X(11) = (X(11)- JVS(52)*X(12))/(JVS(51))
  X(10) = (X(10)- JVS(42)*X(11)- JVS(43)*X(12))/(JVS(41))
  X(9) = (X(9)- JVS(33)*X(10)- JVS(34)*X(11)- JVS(35)*X(12))/(JVS(32))
  X(8) = (X(8)- JVS(26)*X(9)- JVS(27)*X(10)- JVS(28)*X(12))/(JVS(25))
  X(7) = (X(7)- JVS(21)*X(8)- JVS(22)*X(10)- JVS(23)*X(11)- JVS(24)*X(12))/(JVS(20))
  X(6) = (X(6)- JVS(16)*X(8)- JVS(17)*X(9)- JVS(18)*X(10))/(JVS(15))
  X(5) = (X(5)- JVS(13)*X(10)- JVS(14)*X(11))/(JVS(12))
  X(4) = (X(4)- JVS(9)*X(7)- JVS(10)*X(11))/(JVS(8))
  X(3) = (X(3)- JVS(7)*X(12))/(JVS(6))
  X(2) = (X(2)- JVS(5)*X(11))/(JVS(4))
  X(1) = (X(1)- JVS(2)*X(11)- JVS(3)*X(12))/(JVS(1))
      
END SUBROUTINE KppSolve
 
SUBROUTINE KppDecomp( JVS, IER)
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !          Sparse LU factorization
  !   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        IMPLICIT NONE               ! bK  kkp5

      INTEGER  :: IER
      REAL(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0.  !  mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
         !  IF(JVS( LU_DIAG(k)).EQ. 0.)THEN
        IF(ABS(JVS(LU_DIAG(k)))< TINY(a))THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+ 1)- 1
              W( LU_ICOL(kk))= JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)- 1
            j = LU_ICOL(kk)
            a = - W(j) / JVS( LU_DIAG(j))
            W(j) = - a
            DO jj = LU_DIAG(j)+ 1, LU_CROW(j+ 1)- 1
               W( LU_ICOL(jj))= W( LU_ICOL(jj))+  a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+ 1)- 1
            JVS(kk) = W( LU_ICOL(kk))
         END DO
      END DO
      
END SUBROUTINE KppDecomp
 
      REAL(kind=dp) FUNCTION WLAMCH( C)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  !       returns epsilon machine
  !       after LAPACK
  !       replace this by the function from the optimized LAPACK implementation:
!          CALL SLAMCH('E') or CALL DLAMCH('E')
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  !        USE kchem_kpp_Precision
        IMPLICIT NONE               ! bk kkp6
      CHARACTER ::  C
      INTEGER    :: i
      REAL(kind=dp), SAVE  ::  Eps
      REAL(kind=dp)  ::  Suma
      REAL(kind=dp), PARAMETER  ::  ONE=1.0_dp, HALF=0.5_dp
      LOGICAL, SAVE   ::  First=.TRUE.
      
      IF (First) THEN
        First = .FALSE.
        Eps = HALF**(16)
        DO i = 17, 80
          Eps = Eps*HALF
          CALL WLAMCH_ADD(ONE,Eps,Suma)
          IF (Suma.LE.ONE) GOTO 10
        END DO
        PRINT*,'ERROR IN WLAMCH. EPS < ',Eps
        RETURN
10      Eps = Eps*2
        i = i- 1      
      END IF

      WLAMCH = Eps

      END FUNCTION WLAMCH
 
      SUBROUTINE WLAMCH_ADD( A, B, Suma)
  !        USE kchem_kpp_Precision
      IMPLICIT NONE                 ! bK kkp7
      REAL(kind=dp) A, B, Suma
      Suma = A +  B

      END SUBROUTINE WLAMCH_ADD
 
SUBROUTINE Jac_SP(V, F, RCT, JVS)
        IMPLICIT NONE           ! bK kkp8        
  !   V -  Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
  !   F -  Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
  !   RCT -  Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
  !   JVS -  sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


  !   Local variables
  !   B -  Temporary array
  REAL(kind=dp) :: B(21)

 !   B(1) = dA(1)/dV(11)
  B(1) = RCT(1)
  !   B(2) = dA(2)/dV(2)
  B(2) = 8.125e-19_dp*F(2)      !bK
  !   B(4) = dA(3)/dV(5)
  B(4) = 9.897e-13_dp*V(10)     !bK
  !   B(5) = dA(3)/dV(10)       
  B(5) = 9.897e-13_dp*V(5)      !bK
  !   B(6) = dA(4)/dV(3)
  B(6) = 1.405e-10_dp*V(12)     !bK
  !   B(7) = dA(4)/dV(12)
  B(7) = 1.405e-10_dp*V(3)      !bK
  !   B(8) = dA(5)/dV(8)
  B(8) = 8.713e-10_dp*V(12)     !bK
  !   B(9) = dA(5)/dV(12)
  B(9) = 8.713e-10_dp*V(8)      !bK
  !   B(10) = dA(6)/dV(8)
  B(10) = RCT(6)
  !   B(11) = dA(7)/dV(6)
  B(11) = 4.518e-10_dp*V(10)    !bK
  !   B(12) = dA(7)/dV(10)
  B(12) = 4.518e-10_dp*V(6)     !bK
  !   B(13) = dA(8)/dV(9)
  B(13) = 4.195e-10_dp*V(10)    !bK
  !   B(14) = dA(8)/dV(10)
  B(14) = 4.195e-10_dp*V(9)     !bK
  !   B(15) = dA(9)/dV(7)
  B(15) = 4.195e-10_dp*V(10)    !bK
  !   B(16) = dA(9)/dV(10)
  B(16) = 4.195e-10_dp*V(7)     !bK
  !   B(17) = dA(10)/dV(11)
  B(17) = 6.004e-10_dp*V(12)    !bK
  !   B(18) = dA(10)/dV(12)
  B(18) = 6.004e-10_dp*V(11)    !bK
  !   B(19) = dA(11)/dV(7)
  B(19) = 2.566e-10_dp*V(11)    !bK
  !   B(20) = dA(11)/dV(11)
  B(20) = 2.566e-10_dp*V(7)     !bK
  !   B(21) = dA(12)/dV(4)
  B(21) = 7.976e-16_dp          !bK

! Construct the Jacobian terms from B's
  !   JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
  !   JVS(2) = Jac_FULL(1,11)
  JVS(2) = B(17)
  !   JVS(3) = Jac_FULL(1,12)
  JVS(3) = B(18)
  !   JVS(4) = Jac_FULL(2,2)
  JVS(4) = - B(2)
  !   JVS(5) = Jac_FULL(2,11)
  JVS(5) = B(1)
  !   JVS(6) = Jac_FULL(3,3)
  JVS(6) = - B(6)
  !   JVS(7) = Jac_FULL(3,12)
  JVS(7) = - B(7)
  !   JVS(8) = Jac_FULL(4,4)
  JVS(8) = - B(21)
  !   JVS(9) = Jac_FULL(4,7)
  JVS(9) = B(19)
  !   JVS(10) = Jac_FULL(4,11)
  JVS(10) = B(20)
  !   JVS(11) = Jac_FULL(5,2)
  JVS(11) = B(2)
  !   JVS(12) = Jac_FULL(5,5)
  JVS(12) = - B(4)
  !   JVS(13) = Jac_FULL(5,10)
  JVS(13) = - B(5)
  !   JVS(14) = Jac_FULL(5,11)
  JVS(14) = 0
  !   JVS(15) = Jac_FULL(6,6)
  JVS(15) = - B(11)
  !   JVS(16) = Jac_FULL(6,8)
  JVS(16) = B(10)
  !   JVS(17) = Jac_FULL(6,9)
  JVS(17) = B(13)
  !   JVS(18) = Jac_FULL(6,10)
  JVS(18) = - B(12)+ B(14)
  !   JVS(19) = Jac_FULL(7,4)
  JVS(19) = B(21)
  !   JVS(20) = Jac_FULL(7,7)
  JVS(20) = - B(15)- B(19)
  !   JVS(21) = Jac_FULL(7,8)
  JVS(21) = B(8)
  !   JVS(22) = Jac_FULL(7,10)
  JVS(22) = - B(16)
  !   JVS(23) = Jac_FULL(7,11)
  JVS(23) = - B(20)
  !   JVS(24) = Jac_FULL(7,12)
  JVS(24) = B(9)
  !   JVS(25) = Jac_FULL(8,8)
  JVS(25) = - B(8)- B(10)
  !   JVS(26) = Jac_FULL(8,9)
  JVS(26) = B(13)
  !   JVS(27) = Jac_FULL(8,10)
  JVS(27) = B(14)
  !   JVS(28) = Jac_FULL(8,12)
  JVS(28) = - B(9)
  !   JVS(29) = Jac_FULL(9,3)
  JVS(29) = B(6)
  !   JVS(30) = Jac_FULL(9,7)
  JVS(30) = B(15)
  !   JVS(31) = Jac_FULL(9,8)
  JVS(31) = B(10)
  !   JVS(32) = Jac_FULL(9,9)
  JVS(32) = - B(13)
  !   JVS(33) = Jac_FULL(9,10)
  JVS(33) = - B(14)+ B(16)
  !   JVS(34) = Jac_FULL(9,11)
  JVS(34) = 0
  !   JVS(35) = Jac_FULL(9,12)
  JVS(35) = B(7)
  !   JVS(36) = Jac_FULL(10,5)
  JVS(36) = - B(4)
  !   JVS(37) = Jac_FULL(10,6)
  JVS(37) = - B(11)
  !   JVS(38) = Jac_FULL(10,7)
  JVS(38) = - B(15)
  !   JVS(39) = Jac_FULL(10,8)
  JVS(39) = 0
  !   JVS(40) = Jac_FULL(10,9)
  JVS(40) = - B(13)
  !   JVS(41) = Jac_FULL(10,10)
  JVS(41) = - B(5)- B(12)- B(14)- B(16)
  !   JVS(42) = Jac_FULL(10,11)
  JVS(42) = B(1)
  !   JVS(43) = Jac_FULL(10,12)
  JVS(43) = 0
  !   JVS(44) = Jac_FULL(11,4)
  JVS(44) = B(21)
  !   JVS(45) = Jac_FULL(11,5)
  JVS(45) = B(4)
  !   JVS(46) = Jac_FULL(11,6)
  JVS(46) = B(11)
  !   JVS(47) = Jac_FULL(11,7)
  JVS(47) = B(15)- B(19)
  !   JVS(48) = Jac_FULL(11,8)
  JVS(48) = 0
  !   JVS(49) = Jac_FULL(11,9)
  JVS(49) = B(13)
  !   JVS(50) = Jac_FULL(11,10)
  JVS(50) = B(5)+ B(12)+ B(14)+ B(16)
  !   JVS(51) = Jac_FULL(11,11)
  JVS(51) = - B(1)- B(17)- B(20)
  !   JVS(52) = Jac_FULL(11,12)
  JVS(52) = - B(18)
  !   JVS(53) = Jac_FULL(12,3)
  JVS(53) = - B(6)
  !   JVS(54) = Jac_FULL(12,6)
  JVS(54) = B(11)
  !   JVS(55) = Jac_FULL(12,8)
  JVS(55) = - B(8)
  !   JVS(56) = Jac_FULL(12,9)
  JVS(56) = 0
  !   JVS(57) = Jac_FULL(12,10)
  JVS(57) = B(12)
  !   JVS(58) = Jac_FULL(12,11)
  JVS(58) = - B(17)
  !   JVS(59) = Jac_FULL(12,12)
  JVS(59) = - B(7)- B(9)- B(18)
      
END SUBROUTINE Jac_SP
 
  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
     !  Arrhenius function
    IMPLICIT NONE                                           ! bK kkp9
    REAL,     INTENT(IN) :: k_298  !  k at T = 298.15K
    REAL,     INTENT(IN) :: tdep   !  temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp   !  temperature

    INTRINSIC EXP

    k_arr = k_298 *EXP(tdep*(1._dp/temp- 3.3540E-3_dp)) !  1/298.15=3.3540e-3

  END FUNCTION k_arr
 
SUBROUTINE Update_RCONST()
    IMPLICIT NONE               ! bK kkp10
 integer         :: j,k

  k = is

  !   Begin INLINED RCONST


  !   End INLINED RCONST

  RCONST(1) = (0.533_dp)                       ! bK added _dp photo dissociation k of NO2
  !   RCONST(2) = constant rate coefficient
  !   RCONST(3) = constant rate coefficient
  !   RCONST(4) = constant rate coefficient
  !   RCONST(5) = constant rate coefficient
  RCONST(6) = (1.91E-4_dp)                      !bK added _dp photodissociation k of RCHO
  !   RCONST(7) = constant rate coefficient
  !   RCONST(8) = constant rate coefficient
  !   RCONST(9) = constant rate coefficient
  !   RCONST(10) = constant rate coefficient
  !   RCONST(11) = constant rate coefficient
  !   RCONST(12) = constant rate coefficient
      
END SUBROUTINE Update_RCONST
 
  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)
    IMPLICIT NONE                   ! bK kkp11
    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp       !  temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair       !  air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K    !  low pressure limit at 300 K
    REAL, INTENT(IN) :: n          !  exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K  !  high pressure limit at 300 K
    REAL, INTENT(IN) :: m          !  exponent for high pressure limit
    REAL, INTENT(IN) :: fc         !  broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   *zt_help**(n) *cair  !  k_0   at current T
    kinf_T  = kinf_300K *zt_help**(m)         !  k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+ k_ratio)*fc**(1._dp/(1._dp+ LOG10(k_ratio)**2))

  END FUNCTION k_3rd
 
SUBROUTINE initialize_kpp_ctrl(status, iou, modstr)
    IMPLICIT NONE           ! bK  kkp12

   !  I/O
  INTEGER,          INTENT(OUT) :: status
  INTEGER,          INTENT(IN)  :: iou      !  logical I/O unit
  CHARACTER(LEN=*), INTENT(IN)  :: modstr   !  read <modstr>.nml

   !  LOCAL
  REAL(DP) :: tsum
  INTEGER  :: i

   !  check fixed time steps
  tsum = 0.0_dp
  DO i=1, NMAXFIXSTEPS
     IF (t_steps(i) < TINY(0.0_DP))EXIT
     tsum = tsum +  t_steps(i)
  END DO

  nfsteps = i- 1

  l_fixed_step = (nfsteps > 0) .AND.((tsum - 1.0) < TINY(0.0_DP))

  IF (L_VECTOR) THEN
     WRITE(*,*) ' MODE             : VECTOR (LENGTH=',VL_DIM,')'
  ELSE
     WRITE(*,*) ' MODE             : SCALAR'
  END IF
   ! 
  WRITE(*,*) ' DE-INDEXING MODE :',I_LU_DI
   ! 
  WRITE(*,*) ' ICNTRL           : ',icntrl
  WRITE(*,*) ' RCNTRL           : ',rcntrl
   ! 
   !  NOTE: THIS IS ONLY MEANINGFUL FOR VECTORIZED (kp4) ROSENBROCK- METHODS
  IF (L_VECTOR) THEN
     IF (l_fixed_step) THEN
        WRITE(*,*) ' TIME STEPS       : FIXED (',t_steps(1:nfsteps),')'
     ELSE
        WRITE(*,*) ' TIME STEPS       : AUTOMATIC'
     END IF
  ELSE
     WRITE(*,*) ' TIME STEPS       : AUTOMATIC '//&
          &'(t_steps (CTRL_KPP) ignored in SCALAR MODE)'
  END IF
   !  mz_pj_20070531- 

  status = 0


END SUBROUTINE initialize_kpp_ctrl
 
SUBROUTINE error_output(C,ierr,PE)
    IMPLICIT NONE                   ! bK kkp13   

  INTEGER, INTENT(IN) :: ierr
  INTEGER, INTENT(IN) :: PE
  REAL(dp), DIMENSION(:),INTENT(IN) :: C

  write(6,*) 'ERROR in kchem_kpp ',ierr,C(1)


END SUBROUTINE error_output
 
      SUBROUTINE WCOPY(N,X,incX,Y,incY)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  !       copies a vector, x, to a vector, y:  y <-  x
  !       only for incX=incY=1
  !       after BLAS
  !       replace this by the function from the optimized BLAS implementation:
  !           CALL  SCOPY(N,X,1,Y,1)   or   CALL  DCOPY(N,X,1,Y,1)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  !       USE kchem_kpp_Precision
      IMPLICIT NONE                 ! bK kkp14 
      INTEGER  :: i,incX,incY,M,MP1,N
      REAL(kind=dp) :: X(N),Y(N)

      IF (N.LE.0) RETURN

      M = MOD(N,8)
      IF( M .NE. 0)THEN
        DO i = 1,M
          Y(i) = X(i)
        END DO
        IF( N .LT. 8)RETURN
      END IF    
      MP1 = M+ 1
      DO i = MP1,N,8
        Y(i) = X(i)
        Y(i +  1) = X(i +  1)
        Y(i +  2) = X(i +  2)
        Y(i +  3) = X(i +  3)
        Y(i +  4) = X(i +  4)
        Y(i +  5) = X(i +  5)
        Y(i +  6) = X(i +  6)
        Y(i +  7) = X(i +  7)
      END DO

      END SUBROUTINE WCOPY
 
      SUBROUTINE WSCAL(N,Alpha,X,incX)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  !       constant times a vector: x(1:N) <-  Alpha*x(1:N) 
  !       only for incX=incY=1
  !       after BLAS
  !       replace this by the function from the optimized BLAS implementation:
  !           CALL SSCAL(N,Alpha,X,1) or  CALL DSCAL(N,Alpha,X,1)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
        IMPLICIT NONE                   ! bK kkp15
      INTEGER  :: i,incX,M,MP1,N
      REAL(kind=dp)  :: X(N),Alpha
      REAL(kind=dp), PARAMETER  :: ZERO=0.0_dp, ONE=1.0_dp

      IF (Alpha .EQ. ONE) RETURN
      IF (N .LE. 0) RETURN

      M = MOD(N,5)
      IF( M .NE. 0)THEN
        IF (Alpha .EQ. (- ONE))THEN
          DO i = 1,M
            X(i) = - X(i)
          END DO
        ELSEIF (Alpha .EQ. ZERO) THEN
          DO i = 1,M
            X(i) = ZERO
          END DO
        ELSE
          DO i = 1,M
            X(i) = Alpha*X(i)
          END DO
        END IF
        IF( N .LT. 5)RETURN
      END IF
      MP1 = M +  1
      IF (Alpha .EQ. (- ONE))THEN
        DO i = MP1,N,5
          X(i)     = - X(i)
          X(i +  1) = - X(i +  1)
          X(i +  2) = - X(i +  2)
          X(i +  3) = - X(i +  3)
          X(i +  4) = - X(i +  4)
        END DO
      ELSEIF (Alpha .EQ. ZERO) THEN
        DO i = MP1,N,5
          X(i)     = ZERO
          X(i +  1) = ZERO
          X(i +  2) = ZERO
          X(i +  3) = ZERO
          X(i +  4) = ZERO
        END DO
      ELSE
        DO i = MP1,N,5
          X(i)     = Alpha*X(i)
          X(i +  1) = Alpha*X(i +  1)
          X(i +  2) = Alpha*X(i +  2)
          X(i +  3) = Alpha*X(i +  3)
          X(i +  4) = Alpha*X(i +  4)
        END DO
      END IF

      END SUBROUTINE WSCAL
 
      SUBROUTINE WAXPY(N,Alpha,X,incX,Y,incY)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  !       constant times a vector plus a vector: y <-  y +  Alpha*x
  !       only for incX=incY=1
  !       after BLAS
  !       replace this by the function from the optimized BLAS implementation:
  !           CALL SAXPY(N,Alpha,X,1,Y,1) or  CALL DAXPY(N,Alpha,X,1,Y,1)
  !  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
        IMPLICIT NONE           ! bK kkp16
      INTEGER  :: i,incX,incY,M,MP1,N
      REAL(kind=dp) :: X(N),Y(N),Alpha
      REAL(kind=dp), PARAMETER :: ZERO = 0.0_dp

      IF (Alpha .EQ. ZERO) RETURN
      IF (N .LE. 0) RETURN

      M = MOD(N,4)
      IF( M .NE. 0)THEN
        DO i = 1,M
          Y(i) = Y(i) +  Alpha*X(i)
        END DO
        IF( N .LT. 4)RETURN
      END IF
      MP1 = M +  1
      DO i = MP1,N,4
        Y(i) = Y(i) +  Alpha*X(i)
        Y(i +  1) = Y(i +  1) +  Alpha*X(i +  1)
        Y(i +  2) = Y(i +  2) +  Alpha*X(i +  2)
        Y(i +  3) = Y(i +  3) +  Alpha*X(i +  3)
      END DO
      
      END SUBROUTINE WAXPY
 
SUBROUTINE Rosenbrock(N,Y,Tstart,Tend, &
           AbsTol,RelTol,              &
           RCNTRL,ICNTRL,RSTATUS,ISTATUS,IERR)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  
!    Solves the system y'=F(t,y) using a Rosenbrock method defined by:
  !  
  !       G = 1/(H*gamma(1))-  Jac(t0,Y0)
  !       T_i = t0 +  Alpha(i)*H
  !       Y_i = Y0 +  \sum_{j=1}^{i- 1} A(i,j)*K_j
  !       G *K_i = Fun( T_i, Y_i)+  \sum_{j=1}^S C(i,j)/H *K_j + 
  !           gamma(i)*dF/dT(t0, Y0)
  !       Y1 = Y0 +  \sum_{j=1}^S M(j)*K_j
  !  
  !      For details on Rosenbrock methods and their implementation consult:
  !        E. Hairer and G. Wanner
  !        "Solving ODEs II. Stiff and differential- algebraic problems".
  !        Springer series in computational mathematics, Springer- Verlag, 1996.
  !      The codes contained in the book inspired this implementation.
  !  
  !      (C)  Adrian Sandu, August 2004
  !      Virginia Polytechnic Institute and State University
  !      Contact: sandu@cs.vt.edu
  !      Revised by Philipp Miehe and Adrian Sandu, May 2006                  
  !      This implementation is part of KPP -  the Kinetic PreProcessor
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  
  !  ~~~>   INPUT ARGUMENTS:
  !  
  !  -      Y(N)    = vector of initial conditions (at T=Tstart)
  !  -     [Tstart,Tend]  = time range of integration
  !       (if Tstart>Tend the integration is performed backwards in time)
  !  -     RelTol, AbsTol = user precribed accuracy
  !  -  SUBROUTINE  Fun( T, Y, Ydot)= ODE function,
!                       returns Ydot = Y' = F(T,Y)
  !  -  SUBROUTINE  Jac( T, Y, Jcb)= Jacobian of the ODE function,
  !                         returns Jcb = dFun/dY
  !  -     ICNTRL(1:20)    = integer inputs parameters
  !  -     RCNTRL(1:20)    = real inputs parameters
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  
  !  ~~~>     OUTPUT ARGUMENTS:
  !  
  !  -     Y(N)    - > vector of final states (at T- >Tend)
  !  -     ISTATUS(1:20)   - > integer output parameters
  !  -     RSTATUS(1:20)   - > real output parameters
  !  -     IERR            - > job status upon return
  !                          success (positive value) or
  !                          failure (negative value)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  
  !  ~~~>     INPUT PARAMETERS:
  !  
  !      Note: For input parameters equal to zero the default values of the
  !         corresponding variables are used.
  !  
  !      ICNTRL(1) = 1: F = F(y)   Independent of T (AUTONOMOUS)
  !                = 0: F = F(t,y) Depends on T (NON- AUTONOMOUS)
  !  
  !      ICNTRL(2) = 0: AbsTol, RelTol are N- dimensional vectors
  !                = 1: AbsTol, RelTol are scalars
  !  
  !      ICNTRL(3)  - > selection of a particular Rosenbrock method
  !          = 0 :    Rodas3 (default)
  !          = 1 :    Ros2
  !          = 2 :    Ros3
  !          = 3 :    Ros4
  !          = 4 :    Rodas3
  !          = 5 :    Rodas4
  !  
  !      ICNTRL(4)  - > maximum number of integration steps
  !          For ICNTRL(4)=0) the default value of 100000 is used
  !  
  !      RCNTRL(1)  - > Hmin, lower bound for the integration step size
  !            It is strongly recommended to keep Hmin = ZERO
  !      RCNTRL(2)  - > Hmax, upper bound for the integration step size
  !      RCNTRL(3)  - > Hstart, starting value for the integration step size
  !  
  !      RCNTRL(4)  - > FacMin, lower bound on step decrease factor (default=0.2)
  !      RCNTRL(5)  - > FacMax, upper bound on step increase factor (default=6)
  !      RCNTRL(6)  - > FacRej, step decrease factor after multiple rejections
  !                            (default=0.1)
  !      RCNTRL(7)  - > FacSafe, by which the new step is slightly smaller
  !           than the predicted value  (default=0.9)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  
  !  
  !      OUTPUT ARGUMENTS:
  !      - - - - - - - - - - - - - - - - - 
  !  
  !      T           - > T value for which the solution has been computed
  !                       (after successful return T=Tend).
  !  
  !      Y(N)        - > Numerical solution at T
  !  
  !      IDID        - > Reports on successfulness upon return:
  !                      = 1 for success
  !                      < 0 for error (value equals error code)
  !  
  !      ISTATUS(1)  - > No. of function calls
  !      ISTATUS(2)  - > No. of jacobian calls
  !      ISTATUS(3)  - > No. of steps
  !      ISTATUS(4)  - > No. of accepted steps
  !      ISTATUS(5)  - > No. of rejected steps (except at very beginning)
  !      ISTATUS(6)  - > No. of LU decompositions
  !      ISTATUS(7)  - > No. of forward/backward substitutions
  !      ISTATUS(8)  - > No. of singular matrix decompositions
  !  
  !      RSTATUS(1)  - > Texit, the time corresponding to the
  !                       computed Y upon return
  !      RSTATUS(2)  - > Hexit, last accepted step before exit
  !      RSTATUS(3)  - > Hnew, last predicted step (not yet taken)
  !                     For multiple restarts, use Hnew as Hstart 
  !                       in the subsequent run
  !  
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    IMPLICIT NONE               ! bK kkp17
  !  ~~~>  Arguments
   INTEGER,       INTENT(IN)    :: N
   REAL(kind=dp), INTENT(INOUT) :: Y(N)
   REAL(kind=dp), INTENT(IN)    :: Tstart,Tend
   REAL(kind=dp), INTENT(IN)    :: AbsTol(N),RelTol(N)
   INTEGER,       INTENT(IN)    :: ICNTRL(20)
   REAL(kind=dp), INTENT(IN)    :: RCNTRL(20)
   INTEGER,       INTENT(INOUT) :: ISTATUS(20)
   REAL(kind=dp), INTENT(INOUT) :: RSTATUS(20)
   INTEGER, INTENT(OUT)   :: IERR
  !  ~~~>  Parameters of the Rosenbrock method, up to 6 stages
   INTEGER ::  ros_S, rosMethod
   INTEGER, PARAMETER :: RS2=1, RS3=2, RS4=3, RD3=4, RD4=5, RG3=6
   REAL(kind=dp) :: ros_A(15), ros_C(15), ros_M(6), ros_E(6), &
                    ros_Alpha(6), ros_Gamma(6), ros_ELO
   LOGICAL :: ros_NewF(6)
   CHARACTER(LEN=12) :: ros_Name
  !  ~~~>  Local variables
   REAL(kind=dp) :: Roundoff, FacMin, FacMax, FacRej, FacSafe
   REAL(kind=dp) :: Hmin, Hmax, Hstart
   REAL(kind=dp) :: Texit
   INTEGER       :: i, UplimTol, Max_no_steps
   LOGICAL       :: Autonomous, VectorTol
  !  ~~~>   Parameters
   REAL(kind=dp), PARAMETER :: ZERO = 0.0_dp, ONE  = 1.0_dp
   REAL(kind=dp), PARAMETER :: DeltaMin = 1.0E-5_dp

  !  ~~~>  Initialize statistics
   ISTATUS(1:8) = 0
   RSTATUS(1:3) = ZERO

  !  ~~~>  Autonomous or time dependent ODE. Default is time dependent.
   Autonomous = .NOT.(ICNTRL(1) == 0)

  !  ~~~>  For Scalar tolerances (ICNTRL(2).NE.0)  the code uses AbsTol(1) and RelTol(1)
  !     For Vector tolerances (ICNTRL(2) == 0) the code uses AbsTol(1:N) and RelTol(1:N)
   IF (ICNTRL(2) == 0) THEN
      VectorTol = .TRUE.
      UplimTol  = N
   ELSE
      VectorTol = .FALSE.
      UplimTol  = 1
   END IF

  !  ~~~>   Initialize the particular Rosenbrock method selected
   SELECT CASE (ICNTRL(3))
     CASE (1)
       CALL Ros2
     CASE (2)
       CALL Ros3
     CASE (3)
       CALL Ros4
     CASE (0,4)
       CALL Rodas3
     CASE (5)
       CALL Rodas4
     CASE (6)
       CALL Rang3
     CASE DEFAULT
       PRINT *,'Unknown Rosenbrock method: ICNTRL(3)=',ICNTRL(3) 
       CALL ros_ErrorMsg(- 2,Tstart,ZERO,IERR)
       RETURN
   END SELECT

  !  ~~~>   The maximum number of steps admitted
   IF (ICNTRL(4) == 0) THEN
      Max_no_steps = 200000
   ELSEIF (ICNTRL(4) > 0) THEN
      Max_no_steps=ICNTRL(4)
   ELSE
      PRINT *,'User-selected max no. of steps: ICNTRL(4)=',ICNTRL(4)
      CALL ros_ErrorMsg(- 1,Tstart,ZERO,IERR)
      RETURN
   END IF

  !  ~~~>  Unit roundoff (1+ Roundoff>1)
   Roundoff = WLAMCH('E')

  !  ~~~>  Lower bound on the step size: (positive value)
   IF (RCNTRL(1) == ZERO) THEN
      Hmin = ZERO
   ELSEIF (RCNTRL(1) > ZERO) THEN
      Hmin = RCNTRL(1)
   ELSE
      PRINT *,'User-selected Hmin: RCNTRL(1)=',RCNTRL(1)
      CALL ros_ErrorMsg(- 3,Tstart,ZERO,IERR)
      RETURN
   END IF
  !  ~~~>  Upper bound on the step size: (positive value)
   IF (RCNTRL(2) == ZERO) THEN
      Hmax = ABS(Tend-Tstart)
   ELSEIF (RCNTRL(2) > ZERO) THEN
      Hmax = MIN(ABS(RCNTRL(2)),ABS(Tend-Tstart))
   ELSE
      PRINT *,'User-selected Hmax: RCNTRL(2)=',RCNTRL(2)
      CALL ros_ErrorMsg(- 3,Tstart,ZERO,IERR)
      RETURN
   END IF
  !  ~~~>  Starting step size: (positive value)
   IF (RCNTRL(3) == ZERO) THEN
      Hstart = MAX(Hmin,DeltaMin)
   ELSEIF (RCNTRL(3) > ZERO) THEN
      Hstart = MIN(ABS(RCNTRL(3)),ABS(Tend-Tstart))
   ELSE
      PRINT *,'User-selected Hstart: RCNTRL(3)=',RCNTRL(3)
      CALL ros_ErrorMsg(- 3,Tstart,ZERO,IERR)
      RETURN
   END IF
  !  ~~~>  Step size can be changed s.t.  FacMin < Hnew/Hold < FacMax
   IF (RCNTRL(4) == ZERO) THEN
      FacMin = 0.2_dp
   ELSEIF (RCNTRL(4) > ZERO) THEN
      FacMin = RCNTRL(4)
   ELSE
      PRINT *,'User-selected FacMin: RCNTRL(4)=',RCNTRL(4)
      CALL ros_ErrorMsg(- 4,Tstart,ZERO,IERR)
      RETURN
   END IF
   IF (RCNTRL(5) == ZERO) THEN
      FacMax = 6.0_dp
   ELSEIF (RCNTRL(5) > ZERO) THEN
      FacMax = RCNTRL(5)
   ELSE
      PRINT *,'User-selected FacMax: RCNTRL(5)=',RCNTRL(5)
      CALL ros_ErrorMsg(- 4,Tstart,ZERO,IERR)
      RETURN
   END IF
  !  ~~~>   FacRej: Factor to decrease step after 2 succesive rejections
   IF (RCNTRL(6) == ZERO) THEN
      FacRej = 0.1_dp
   ELSEIF (RCNTRL(6) > ZERO) THEN
      FacRej = RCNTRL(6)
   ELSE
      PRINT *,'User-selected FacRej: RCNTRL(6)=',RCNTRL(6)
      CALL ros_ErrorMsg(- 4,Tstart,ZERO,IERR)
      RETURN
   END IF
  !  ~~~>   FacSafe: Safety Factor in the computation of new step size
   IF (RCNTRL(7) == ZERO) THEN
      FacSafe = 0.9_dp
   ELSEIF (RCNTRL(7) > ZERO) THEN
      FacSafe = RCNTRL(7)
   ELSE
      PRINT *,'User-selected FacSafe: RCNTRL(7)=',RCNTRL(7)
      CALL ros_ErrorMsg(- 4,Tstart,ZERO,IERR)
      RETURN
   END IF
  !  ~~~>  Check if tolerances are reasonable
    DO i=1,UplimTol
      IF((AbsTol(i) <= ZERO) .OR. (RelTol(i) <= 10.0_dp*Roundoff) &
         .OR. (RelTol(i) >= 1.0_dp))THEN
        PRINT *,' AbsTol(',i,') = ',AbsTol(i)
        PRINT *,' RelTol(',i,') = ',RelTol(i)
        CALL ros_ErrorMsg(- 5,Tstart,ZERO,IERR)
        RETURN
      END IF
    END DO


  !  ~~~>  CALL Rosenbrock method
   CALL ros_Integrator(Y, Tstart, Tend, Texit,   &
        AbsTol, RelTol,                          &
  !    Integration parameters
        Autonomous, VectorTol, Max_no_steps,     &
        Roundoff, Hmin, Hmax, Hstart,            &
        FacMin, FacMax, FacRej, FacSafe,         &
  !    Error indicator
        IERR)

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CONTAINS  !   SUBROUTINES internal to Rosenbrock
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
 SUBROUTINE ros_ErrorMsg(Code,T,H,IERR)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
  !      Handles all error messages
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
    IMPLICIT NONE                   ! bK kkp18  
   REAL(kind=dp), INTENT(IN) :: T, H
   INTEGER, INTENT(IN)  :: Code
   INTEGER, INTENT(OUT) :: IERR
   
   IERR = Code
   PRINT *, &
     'Forced exit from Rosenbrock due to the following error:' 
     
   SELECT CASE (Code)
    CASE (- 1)    
      PRINT *,'--> Improper value for maximal no of steps'
    CASE (- 2)    
      PRINT *,'--> Selected Rosenbrock method not implemented'
    CASE (- 3)    
      PRINT *,'--> Hmin/Hmax/Hstart must be positive'
    CASE (- 4)    
      PRINT *,'--> FacMin/FacMax/FacRej must be positive'
    CASE (- 5) 
      PRINT *,'--> Improper tolerance values'
    CASE (- 6) 
      PRINT *,'--> No of steps exceeds maximum bound'
    CASE (- 7) 
      PRINT *,'--> Step size too small: T + 10*H = T',&
            ' or H < Roundoff'
    CASE (- 8)    
      PRINT *,'--> Matrix is repeatedly singular'
    CASE DEFAULT
      PRINT *,'Unknown Error code: ',Code
   END SELECT
   
   PRINT *, "T=", T, "and H=", H
     
 END SUBROUTINE ros_ErrorMsg

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE ros_Integrator (Y, Tstart, Tend, T,  &
        AbsTol, RelTol,                          &
  !  ~~~> Integration parameters
        Autonomous, VectorTol, Max_no_steps,     &
        Roundoff, Hmin, Hmax, Hstart,            &
        FacMin, FacMax, FacRej, FacSafe,         &
  !  ~~~> Error indicator
        IERR)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !     Template for the implementation of a generic Rosenbrock method
  !        defined by ros_S (no of stages)
  !        and its coefficients ros_{A,C,M,E,Alpha,Gamma}
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    IMPLICIT NONE           ! bK kkp19
  !  ~~~> Input: the initial condition at Tstart; Output: the solution at T
   REAL(kind=dp), INTENT(INOUT) :: Y(N)
  !  ~~~> Input: integration interval
   REAL(kind=dp), INTENT(IN) :: Tstart,Tend
  !  ~~~> Output: time at which the solution is returned (T=Tend if success)
   REAL(kind=dp), INTENT(OUT) ::  T
  !  ~~~> Input: tolerances
   REAL(kind=dp), INTENT(IN) ::  AbsTol(N), RelTol(N)
  !  ~~~> Input: integration parameters
   LOGICAL, INTENT(IN) :: Autonomous, VectorTol
   REAL(kind=dp), INTENT(IN) :: Hstart, Hmin, Hmax
   INTEGER, INTENT(IN) :: Max_no_steps
   REAL(kind=dp), INTENT(IN) :: Roundoff, FacMin, FacMax, FacRej, FacSafe
  !  ~~~> Output: Error indicator
   INTEGER, INTENT(OUT) :: IERR
  !   ~~~~ Local variables
   REAL(kind=dp) :: Ynew(N), Fcn0(N), Fcn(N)
   REAL(kind=dp) :: K(N*ros_S), dFdT(N)
#ifdef FULL_ALGEBRA    
   REAL(kind=dp) :: Jac0(N,N), Ghimj(N,N)
#else
   REAL(kind=dp) :: Jac0(LU_NONZERO), Ghimj(LU_NONZERO)
#endif
   REAL(kind=dp) :: H, Hnew, HC, HG, Fac, Tau
   REAL(kind=dp) :: Err, Yerr(N)
   INTEGER :: Pivot(N), Direction, ioffset, j, istage
   LOGICAL :: RejectLastH, RejectMoreH, Singular
  !  ~~~>  Local parameters
   REAL(kind=dp), PARAMETER :: ZERO = 0.0_dp, ONE  = 1.0_dp
   REAL(kind=dp), PARAMETER :: DeltaMin = 1.0E-5_dp
  !  ~~~>  Locally called functions
  !      REAL(kind=dp) WLAMCH
  !      EXTERNAL WLAMCH
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  !  ~~~>  Initial preparations
   T = Tstart
   RSTATUS(Nhexit) = ZERO
   H = MIN( MAX(ABS(Hmin),ABS(Hstart)), ABS(Hmax))
   IF (ABS(H) <= 10.0_dp*Roundoff) H = DeltaMin

   IF (Tend  >=  Tstart) THEN
     Direction = + 1
   ELSE
     Direction = - 1
   END IF
   H = Direction*H

   RejectLastH=.FALSE.
   RejectMoreH=.FALSE.

  !  ~~~> Time loop begins below

TimeLoop: DO WHILE((Direction > 0).AND.((T- Tend)+ Roundoff <= ZERO) &
       .OR. (Direction < 0).AND.((Tend-T)+ Roundoff <= ZERO))

   IF(ISTATUS(Nstp) > Max_no_steps)THEN   !  Too many steps
      CALL ros_ErrorMsg(- 6,T,H,IERR)
      RETURN
   END IF
   IF(((T+ 0.1_dp*H) == T).OR.(H <= Roundoff))THEN   !  Step size too small
      CALL ros_ErrorMsg(- 7,T,H,IERR)
      RETURN
   END IF

  !  ~~~>  Limit H if necessary to avoid going beyond Tend
   H = MIN(H,ABS(Tend-T))

  !  ~~~>   Compute the function at current time
   CALL FunTemplate(T,Y,Fcn0)
   ISTATUS(Nfun) = ISTATUS(Nfun) +  1

  !  ~~~>  Compute the function derivative with respect to T
   IF (.NOT.Autonomous) THEN
      CALL ros_FunTimeDerivative(T, Roundoff, Y, &
                Fcn0, dFdT)
   END IF

  !  ~~~>   Compute the Jacobian at current time
   CALL JacTemplate(T,Y,Jac0)
   ISTATUS(Njac) = ISTATUS(Njac) +  1

  !  ~~~>  Repeat step calculation until current step accepted
UntilAccepted: DO

   CALL ros_PrepareMatrix(H,Direction,ros_Gamma(1), &
          Jac0,Ghimj,Pivot,Singular)
   IF (Singular) THEN  !  More than 5 consecutive failed decompositions
       CALL ros_ErrorMsg(- 8,T,H,IERR)
       RETURN
   END IF

  !  ~~~>   Compute the stages
Stage: DO istage = 1, ros_S

       !  Current istage offset. Current istage vector is K(ioffset+ 1:ioffset+ N)
       ioffset = N*(istage-1)

       !  For the 1st istage the function has been computed previously
       IF(istage == 1)THEN
          ! slim: CALL WCOPY(N,Fcn0,1,Fcn,1)
	 Fcn(1:N) = Fcn0(1:N)
       !  istage>1 and a new function evaluation is needed at the current istage
       ELSEIF(ros_NewF(istage))THEN
          ! slim: CALL WCOPY(N,Y,1,Ynew,1)
	 Ynew(1:N) = Y(1:N)
         DO j = 1, istage-1
           CALL WAXPY(N,ros_A((istage-1)*(istage-2)/2+ j), &
            K(N*(j- 1)+ 1),1,Ynew,1)
         END DO
         Tau = T +  ros_Alpha(istage)*Direction*H
         CALL FunTemplate(Tau,Ynew,Fcn)
         ISTATUS(Nfun) = ISTATUS(Nfun) +  1
       END IF  !  if istage == 1 elseif ros_NewF(istage)
        ! slim: CALL WCOPY(N,Fcn,1,K(ioffset+ 1),1)
       K(ioffset+ 1:ioffset+ N) = Fcn(1:N)
       DO j = 1, istage-1
         HC = ros_C((istage-1)*(istage-2)/2+ j)/(Direction*H)
         CALL WAXPY(N,HC,K(N*(j- 1)+ 1),1,K(ioffset+ 1),1)
       END DO
       IF ((.NOT. Autonomous).AND.(ros_Gamma(istage).NE.ZERO))THEN
         HG = Direction*H*ros_Gamma(istage)
         CALL WAXPY(N,HG,dFdT,1,K(ioffset+ 1),1)
       END IF
       CALL ros_Solve(Ghimj, Pivot, K(ioffset+ 1))

   END DO Stage


  !  ~~~>  Compute the new solution
    ! slim: CALL WCOPY(N,Y,1,Ynew,1)
   Ynew(1:N) = Y(1:N)
   DO j=1,ros_S
         CALL WAXPY(N,ros_M(j),K(N*(j- 1)+ 1),1,Ynew,1)
   END DO

  !  ~~~>  Compute the error estimation
    ! slim: CALL WSCAL(N,ZERO,Yerr,1)
   Yerr(1:N) = ZERO
   DO j=1,ros_S
        CALL WAXPY(N,ros_E(j),K(N*(j- 1)+ 1),1,Yerr,1)
   END DO
   Err = ros_ErrorNorm(Y, Ynew, Yerr, AbsTol, RelTol, VectorTol)

  !  ~~~> New step size is bounded by FacMin <= Hnew/H <= FacMax
   Fac  = MIN(FacMax,MAX(FacMin,FacSafe/Err**(ONE/ros_ELO)))
   Hnew = H*Fac

  !  ~~~>  Check the error magnitude and adjust step size
   ISTATUS(Nstp) = ISTATUS(Nstp) +  1
   IF((Err <= ONE).OR.(H <= Hmin))THEN   ! ~~~> Accept step
      ISTATUS(Nacc) = ISTATUS(Nacc) +  1
       ! slim: CALL WCOPY(N,Ynew,1,Y,1)
      Y(1:N) = Ynew(1:N)
      T = T +  Direction*H
      Hnew = MAX(Hmin,MIN(Hnew,Hmax))
      IF (RejectLastH) THEN   !  No step size increase after a rejected step
         Hnew = MIN(Hnew,H)
      END IF
      RSTATUS(Nhexit) = H
      RSTATUS(Nhnew)  = Hnew
      RSTATUS(Ntexit) = T
      RejectLastH = .FALSE.
      RejectMoreH = .FALSE.
      H = Hnew
      EXIT UntilAccepted  !  EXIT THE LOOP: WHILE STEP NOT ACCEPTED
   ELSE            ! ~~~> Reject step
      IF (RejectMoreH) THEN
         Hnew = H*FacRej
      END IF
      RejectMoreH = RejectLastH
      RejectLastH = .TRUE.
      H = Hnew
      IF (ISTATUS(Nacc) >= 1)  ISTATUS(Nrej) = ISTATUS(Nrej) +  1
   END IF  !  Err <= 1

   END DO UntilAccepted

   END DO TimeLoop

  !  ~~~> Succesful exit
   IERR = 1   ! ~~~> The integration was successful

  END SUBROUTINE ros_Integrator


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  REAL(kind=dp) FUNCTION ros_ErrorNorm(Y, Ynew, Yerr, &
                               AbsTol, RelTol, VectorTol)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  ~~~> Computes the "scaled norm" of the error vector Yerr
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPLICIT NONE           ! bK kkp20
  !   Input arguments
   REAL(kind=dp), INTENT(IN) :: Y(N), Ynew(N), &
          Yerr(N), AbsTol(N), RelTol(N)
   LOGICAL, INTENT(IN) ::  VectorTol
  !   Local variables
   REAL(kind=dp) :: Err, Scale, Ymax
   INTEGER  :: i
   REAL(kind=dp), PARAMETER :: ZERO = 0.0_dp

   Err = ZERO
   DO i=1,N
     Ymax = MAX(ABS(Y(i)),ABS(Ynew(i)))
     IF (VectorTol) THEN
       Scale = AbsTol(i)+ RelTol(i)*Ymax
     ELSE
       Scale = AbsTol(1)+ RelTol(1)*Ymax
     END IF
     Err = Err+ (Yerr(i)/Scale)**2
   END DO
   Err  = SQRT(Err/N)

   ros_ErrorNorm = MAX(Err,1.0d-10)

  END FUNCTION ros_ErrorNorm


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE ros_FunTimeDerivative(T, Roundoff, Y, &
                Fcn0, dFdT)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  ~~~> The time partial derivative of the function by finite differences
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPLICIT NONE       !bK kkp22
  !  ~~~> Input arguments
   REAL(kind=dp), INTENT(IN) :: T, Roundoff, Y(N), Fcn0(N)
  !  ~~~> Output arguments
   REAL(kind=dp), INTENT(OUT) :: dFdT(N)
  !  ~~~> Local variables
   REAL(kind=dp) :: Delta
   REAL(kind=dp), PARAMETER :: ONE = 1.0_dp, DeltaMin = 1.0E-6_dp

   Delta = SQRT(Roundoff)*MAX(DeltaMin,ABS(T))
   CALL FunTemplate(T+ Delta,Y,dFdT)
   ISTATUS(Nfun) = ISTATUS(Nfun) +  1
   CALL WAXPY(N,(- ONE),Fcn0,1,dFdT,1)
   CALL WSCAL(N,(ONE/Delta),dFdT,1)

  END SUBROUTINE ros_FunTimeDerivative


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE ros_PrepareMatrix(H, Direction, gam, &
             Jac0, Ghimj, Pivot, Singular)
  !   - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - - 
  !    Prepares the LHS matrix for stage calculations
  !    1.  Construct Ghimj = 1/(H*ham) -  Jac0
  !        "(Gamma H) Inverse Minus Jacobian"
  !    2.  Repeat LU decomposition of Ghimj until successful.
  !         - half the step size if LU decomposition fails and retry
  !         - exit after 5 consecutive fails
  !   - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - -  - - - 
    IMPLICIT NONE       ! bK kkp23
  !  ~~~> Input arguments
#ifdef FULL_ALGEBRA    
   REAL(kind=dp), INTENT(IN) ::  Jac0(N,N)
#else
   REAL(kind=dp), INTENT(IN) ::  Jac0(LU_NONZERO)
#endif   
   REAL(kind=dp), INTENT(IN) ::  gam
   INTEGER, INTENT(IN) ::  Direction
  !  ~~~> Output arguments
#ifdef FULL_ALGEBRA    
   REAL(kind=dp), INTENT(OUT) :: Ghimj(N,N)
#else
   REAL(kind=dp), INTENT(OUT) :: Ghimj(LU_NONZERO)
#endif   
   LOGICAL, INTENT(OUT) ::  Singular
   INTEGER, INTENT(OUT) ::  Pivot(N)
  !  ~~~> Inout arguments
   REAL(kind=dp), INTENT(INOUT) :: H    !  step size is decreased when LU fails
  !  ~~~> Local variables
   INTEGER  :: i, ISING, Nconsecutive
   REAL(kind=dp) :: ghinv
   REAL(kind=dp), PARAMETER :: ONE  = 1.0_dp, HALF = 0.5_dp

   Nconsecutive = 0
   Singular = .TRUE.

   DO WHILE (Singular)

  !  ~~~>    Construct Ghimj = 1/(H*gam) -  Jac0
#ifdef FULL_ALGEBRA    
      ! slim: CALL WCOPY(N*N,Jac0,1,Ghimj,1)
      ! slim: CALL WSCAL(N*N,(- ONE),Ghimj,1)
     Ghimj = - Jac0
     ghinv = ONE/(Direction*H*gam)
     DO i=1,N
       Ghimj(i,i) = Ghimj(i,i)+ ghinv
     END DO
#else
      ! slim: CALL WCOPY(LU_NONZERO,Jac0,1,Ghimj,1)
      ! slim: CALL WSCAL(LU_NONZERO,(- ONE),Ghimj,1)
     Ghimj(1:LU_NONZERO) = - Jac0(1:LU_NONZERO)
     ghinv = ONE/(Direction*H*gam)
     DO i=1,N
       Ghimj(LU_DIAG(i))= Ghimj(LU_DIAG(i))+ ghinv
     END DO
#endif   
  !  ~~~>    Compute LU decomposition
     CALL ros_Decomp( Ghimj, Pivot, ISING)
     IF (ISING == 0) THEN
  !  ~~~>    If successful done
        Singular = .FALSE.
     ELSE  !  ISING .ne. 0
  !  ~~~>    If unsuccessful half the step size; if 5 consecutive fails then return
        ISTATUS(Nsng) = ISTATUS(Nsng) +  1
        Nconsecutive = Nconsecutive+1
        Singular = .TRUE.
        PRINT*,'Warning: LU Decomposition returned ISING = ',ISING
        IF (Nconsecutive <= 5) THEN  !  Less than 5 consecutive failed decompositions
           H = H*HALF
        ELSE   !  More than 5 consecutive failed decompositions
           RETURN
        END IF   !  Nconsecutive
      END IF     !  ISING

   END DO  !  WHILE Singular

  END SUBROUTINE ros_PrepareMatrix


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE ros_Decomp( A, Pivot, ISING)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !    Template for the LU decomposition
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  ~~~> Inout variables
    IMPLICIT NONE               !bk kkp24
#ifdef FULL_ALGEBRA    
   REAL(kind=dp), INTENT(INOUT) :: A(N,N)
#else   
   REAL(kind=dp), INTENT(INOUT) :: A(LU_NONZERO)
#endif
  !  ~~~> Output variables
   INTEGER, INTENT(OUT) :: Pivot(N), ISING

#ifdef FULL_ALGEBRA    
   CALL  DGETRF( N, N, A, N, Pivot, ISING)
#else   
   CALL KppDecomp(A, ISING)
   Pivot(1) = 1
#endif
   ISTATUS(Ndec) = ISTATUS(Ndec) +  1

  END SUBROUTINE ros_Decomp


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE ros_Solve( A, Pivot, b)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !    Template for the forward/backward substitution (using pre-computed LU decomposition)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  ~~~> Input variables
    IMPLICIT NONE               !bk kkp25

#ifdef FULL_ALGEBRA    
   REAL(kind=dp), INTENT(IN) :: A(N,N)
   INTEGER :: ISING
#else   
   REAL(kind=dp), INTENT(IN) :: A(LU_NONZERO)
#endif
   INTEGER, INTENT(IN) :: Pivot(N)
  !  ~~~> InOut variables
   REAL(kind=dp), INTENT(INOUT) :: b(N)

#ifdef FULL_ALGEBRA    
   CALL  DGETRS( 'N',N ,1,A,N,Pivot,b,N,ISING)
   IF(Info < 0)THEN
      PRINT*,"Error in DGETRS. ISING=",ISING
   END IF  
#else   
   CALL KppSolve( A, b)
#endif

   ISTATUS(Nsol) = ISTATUS(Nsol) +  1

  END SUBROUTINE ros_Solve



  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Ros2
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   - - -  AN L- STABLE METHOD, 2 stages, order 2
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   IMPLICIT NONE               !bk kkp26
   DOUBLE PRECISION g

    g = 1.0_dp +  1.0_dp/SQRT(2.0_dp)
    rosMethod = RS2
  !  ~~~> Name of the method
    ros_Name = 'ROS-2'
  !  ~~~> Number of stages
    ros_S = 2

  !  ~~~> The coefficient matrices A and C are strictly lower triangular.
  !     The lower triangular (subdiagonal) elements are stored in row- wise order:
  !     A(2,1) = ros_A(1), A(3,1)=ros_A(2), A(3,2)=ros_A(3), etc.
  !     The general mapping formula is:
  !         A(i,j) = ros_A( (i- 1)*(i- 2)/2 +  j)
  !         C(i,j) = ros_C( (i- 1)*(i- 2)/2 +  j)

    ros_A(1) = (1.0_dp)/g
    ros_C(1) = (- 2.0_dp)/g
  !  ~~~> Does the stage i require a new function evaluation (ros_NewF(i)=TRUE)
  !     or does it re-use the function evaluation from stage i- 1 (ros_NewF(i)=FALSE)
    ros_NewF(1) = .TRUE.
    ros_NewF(2) = .TRUE.
  !  ~~~> M_i = Coefficients for new step solution
    ros_M(1)= (3.0_dp)/(2.0_dp*g)
    ros_M(2)= (1.0_dp)/(2.0_dp*g)
  !   E_i = Coefficients for error estimator
    ros_E(1) = 1.0_dp/(2.0_dp*g)
    ros_E(2) = 1.0_dp/(2.0_dp*g)
  !  ~~~> ros_ELO = estimator of local order -  the minimum between the
  !      main and the embedded scheme orders plus one
    ros_ELO = 2.0_dp
  !  ~~~> Y_stage_i ~ Y( T +  H*Alpha_i)
    ros_Alpha(1) = 0.0_dp
    ros_Alpha(2) = 1.0_dp
  !  ~~~> Gamma_i = \sum_j  gamma_{i,j}
    ros_Gamma(1) = g
    ros_Gamma(2) =- g

 END SUBROUTINE Ros2


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Ros3
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   - - -  AN L- STABLE METHOD, 3 stages, order 3, 2 function evaluations
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   IMPLICIT NONE               !bk kkp27
   rosMethod = RS3
  !  ~~~> Name of the method
   ros_Name = 'ROS-3'
  !  ~~~> Number of stages
   ros_S = 3

  !  ~~~> The coefficient matrices A and C are strictly lower triangular.
  !     The lower triangular (subdiagonal) elements are stored in row- wise order:
  !     A(2,1) = ros_A(1), A(3,1)=ros_A(2), A(3,2)=ros_A(3), etc.
  !     The general mapping formula is:
  !         A(i,j) = ros_A( (i- 1)*(i- 2)/2 +  j)
  !         C(i,j) = ros_C( (i- 1)*(i- 2)/2 +  j)

   ros_A(1)= 1.0_dp
   ros_A(2)= 1.0_dp
   ros_A(3)= 0.0_dp

   ros_C(1) = - 0.10156171083877702091975600115545E+01_dp
   ros_C(2) =  0.40759956452537699824805835358067E+01_dp
   ros_C(3) =  0.92076794298330791242156818474003E+01_dp
  !  ~~~> Does the stage i require a new function evaluation (ros_NewF(i)=TRUE)
  !     or does it re-use the function evaluation from stage i- 1 (ros_NewF(i)=FALSE)
   ros_NewF(1) = .TRUE.
   ros_NewF(2) = .TRUE.
   ros_NewF(3) = .FALSE.
  !  ~~~> M_i = Coefficients for new step solution
   ros_M(1) =  0.1E+01_dp
   ros_M(2) =  0.61697947043828245592553615689730E+01_dp
   ros_M(3) = - 0.42772256543218573326238373806514_dp
  !   E_i = Coefficients for error estimator
   ros_E(1) =  0.5_dp
   ros_E(2) = - 0.29079558716805469821718236208017E+01_dp
   ros_E(3) =  0.22354069897811569627360909276199_dp
  !  ~~~> ros_ELO = estimator of local order -  the minimum between the
  !      main and the embedded scheme orders plus 1
   ros_ELO = 3.0_dp
  !  ~~~> Y_stage_i ~ Y( T +  H*Alpha_i)
   ros_Alpha(1)= 0.0_dp
   ros_Alpha(2)= 0.43586652150845899941601945119356_dp
   ros_Alpha(3)= 0.43586652150845899941601945119356_dp
  !  ~~~> Gamma_i = \sum_j  gamma_{i,j}
   ros_Gamma(1)= 0.43586652150845899941601945119356_dp
   ros_Gamma(2)= 0.24291996454816804366592249683314_dp
   ros_Gamma(3)= 0.21851380027664058511513169485832E+01_dp

  END SUBROUTINE Ros3

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Ros4
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !       L- STABLE ROSENBROCK METHOD OF ORDER 4, WITH 4 STAGES
  !       L- STABLE EMBEDDED ROSENBROCK METHOD OF ORDER 3
  !  
  !        E. HAIRER AND G. WANNER, SOLVING ORDINARY DIFFERENTIAL
  !        EQUATIONS II. STIFF AND DIFFERENTIAL- ALGEBRAIC PROBLEMS.
  !        SPRINGER SERIES IN COMPUTATIONAL MATHEMATICS,
  !        SPRINGER- VERLAG (1990)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPLICIT NONE               !bk kkp28

   rosMethod = RS4
  !  ~~~> Name of the method
   ros_Name = 'ROS-4'
  !  ~~~> Number of stages
   ros_S = 4

  !  ~~~> The coefficient matrices A and C are strictly lower triangular.
  !     The lower triangular (subdiagonal) elements are stored in row- wise order:
  !     A(2,1) = ros_A(1), A(3,1)=ros_A(2), A(3,2)=ros_A(3), etc.
  !     The general mapping formula is:
  !         A(i,j) = ros_A( (i- 1)*(i- 2)/2 +  j)
  !         C(i,j) = ros_C( (i- 1)*(i- 2)/2 +  j)

   ros_A(1) = 0.2000000000000000E+01_dp
   ros_A(2) = 0.1867943637803922E+01_dp
   ros_A(3) = 0.2344449711399156_dp
   ros_A(4) = ros_A(2)
   ros_A(5) = ros_A(3)
   ros_A(6) = 0.0_dp

   ros_C(1) =- 0.7137615036412310E+01_dp
   ros_C(2) = 0.2580708087951457E+01_dp
   ros_C(3) = 0.6515950076447975_dp
   ros_C(4) =- 0.2137148994382534E+01_dp
   ros_C(5) =- 0.3214669691237626_dp
   ros_C(6) =- 0.6949742501781779_dp
  !  ~~~> Does the stage i require a new function evaluation (ros_NewF(i)=TRUE)
  !     or does it re-use the function evaluation from stage i- 1 (ros_NewF(i)=FALSE)
   ros_NewF(1)  = .TRUE.
   ros_NewF(2)  = .TRUE.
   ros_NewF(3)  = .TRUE.
   ros_NewF(4)  = .FALSE.
  !  ~~~> M_i = Coefficients for new step solution
   ros_M(1) = 0.2255570073418735E+01_dp
   ros_M(2) = 0.2870493262186792_dp
   ros_M(3) = 0.4353179431840180_dp
   ros_M(4) = 0.1093502252409163E+01_dp
  !  ~~~> E_i  = Coefficients for error estimator
   ros_E(1) =- 0.2815431932141155_dp
   ros_E(2) =- 0.7276199124938920E-01_dp
   ros_E(3) =- 0.1082196201495311_dp
   ros_E(4) =- 0.1093502252409163E+01_dp
  !  ~~~> ros_ELO  = estimator of local order -  the minimum between the
  !      main and the embedded scheme orders plus 1
   ros_ELO  = 4.0_dp
  !  ~~~> Y_stage_i ~ Y( T +  H*Alpha_i)
   ros_Alpha(1) = 0.0_dp
   ros_Alpha(2) = 0.1145640000000000E+01_dp
   ros_Alpha(3) = 0.6552168638155900_dp
   ros_Alpha(4) = ros_Alpha(3)
  !  ~~~> Gamma_i = \sum_j  gamma_{i,j}
   ros_Gamma(1) = 0.5728200000000000_dp
   ros_Gamma(2) =- 0.1769193891319233E+01_dp
   ros_Gamma(3) = 0.7592633437920482_dp
   ros_Gamma(4) =- 0.1049021087100450_dp

  END SUBROUTINE Ros4

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Rodas3
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   - - -  A STIFFLY- STABLE METHOD, 4 stages, order 3
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   IMPLICIT NONE               !bk kkp29

   rosMethod = RD3
  !  ~~~> Name of the method
   ros_Name = 'RODAS-3'
  !  ~~~> Number of stages
   ros_S = 4

  !  ~~~> The coefficient matrices A and C are strictly lower triangular.
  !     The lower triangular (subdiagonal) elements are stored in row- wise order:
  !     A(2,1) = ros_A(1), A(3,1)=ros_A(2), A(3,2)=ros_A(3), etc.
  !     The general mapping formula is:
  !         A(i,j) = ros_A( (i- 1)*(i- 2)/2 +  j)
  !         C(i,j) = ros_C( (i- 1)*(i- 2)/2 +  j)

   ros_A(1) = 0.0_dp
   ros_A(2) = 2.0_dp
   ros_A(3) = 0.0_dp
   ros_A(4) = 2.0_dp
   ros_A(5) = 0.0_dp
   ros_A(6) = 1.0_dp

   ros_C(1) = 4.0_dp
   ros_C(2) = 1.0_dp
   ros_C(3) =- 1.0_dp
   ros_C(4) = 1.0_dp
   ros_C(5) =- 1.0_dp
   ros_C(6) =- (8.0_dp/3.0_dp)

  !  ~~~> Does the stage i require a new function evaluation (ros_NewF(i)=TRUE)
  !     or does it re-use the function evaluation from stage i- 1 (ros_NewF(i)=FALSE)
   ros_NewF(1)  = .TRUE.
   ros_NewF(2)  = .FALSE.
   ros_NewF(3)  = .TRUE.
   ros_NewF(4)  = .TRUE.
  !  ~~~> M_i = Coefficients for new step solution
   ros_M(1) = 2.0_dp
   ros_M(2) = 0.0_dp
   ros_M(3) = 1.0_dp
   ros_M(4) = 1.0_dp
  !  ~~~> E_i  = Coefficients for error estimator
   ros_E(1) = 0.0_dp
   ros_E(2) = 0.0_dp
   ros_E(3) = 0.0_dp
   ros_E(4) = 1.0_dp
  !  ~~~> ros_ELO  = estimator of local order -  the minimum between the
  !      main and the embedded scheme orders plus 1
   ros_ELO  = 3.0_dp
  !  ~~~> Y_stage_i ~ Y( T +  H*Alpha_i)
   ros_Alpha(1) = 0.0_dp
   ros_Alpha(2) = 0.0_dp
   ros_Alpha(3) = 1.0_dp
   ros_Alpha(4) = 1.0_dp
  !  ~~~> Gamma_i = \sum_j  gamma_{i,j}
   ros_Gamma(1) = 0.5_dp
   ros_Gamma(2) = 1.5_dp
   ros_Gamma(3) = 0.0_dp
   ros_Gamma(4) = 0.0_dp

  END SUBROUTINE Rodas3

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Rodas4
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !       STIFFLY- STABLE ROSENBROCK METHOD OF ORDER 4, WITH 6 STAGES
  !  
  !        E. HAIRER AND G. WANNER, SOLVING ORDINARY DIFFERENTIAL
  !        EQUATIONS II. STIFF AND DIFFERENTIAL- ALGEBRAIC PROBLEMS.
  !        SPRINGER SERIES IN COMPUTATIONAL MATHEMATICS,
  !        SPRINGER- VERLAG (1996)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPLICIT NONE               !bk kkp30

    rosMethod = RD4
  !  ~~~> Name of the method
    ros_Name = 'RODAS-4'
  !  ~~~> Number of stages
    ros_S = 6

  !  ~~~> Y_stage_i ~ Y( T +  H*Alpha_i)
    ros_Alpha(1) = 0.000_dp
    ros_Alpha(2) = 0.386_dp
    ros_Alpha(3) = 0.210_dp
    ros_Alpha(4) = 0.630_dp
    ros_Alpha(5) = 1.000_dp
    ros_Alpha(6) = 1.000_dp

  !  ~~~> Gamma_i = \sum_j  gamma_{i,j}
    ros_Gamma(1) = 0.2500000000000000_dp
    ros_Gamma(2) =- 0.1043000000000000_dp
    ros_Gamma(3) = 0.1035000000000000_dp
    ros_Gamma(4) =- 0.3620000000000023E-01_dp
    ros_Gamma(5) = 0.0_dp
    ros_Gamma(6) = 0.0_dp

  !  ~~~> The coefficient matrices A and C are strictly lower triangular.
  !     The lower triangular (subdiagonal) elements are stored in row- wise order:
  !     A(2,1) = ros_A(1), A(3,1)=ros_A(2), A(3,2)=ros_A(3), etc.
  !     The general mapping formula is:  A(i,j) = ros_A( (i- 1)*(i- 2)/2 +  j)
  !                    C(i,j) = ros_C( (i- 1)*(i- 2)/2 +  j)

    ros_A(1) = 0.1544000000000000E+01_dp
    ros_A(2) = 0.9466785280815826_dp
    ros_A(3) = 0.2557011698983284_dp
    ros_A(4) = 0.3314825187068521E+01_dp
    ros_A(5) = 0.2896124015972201E+01_dp
    ros_A(6) = 0.9986419139977817_dp
    ros_A(7) = 0.1221224509226641E+01_dp
    ros_A(8) = 0.6019134481288629E+01_dp
    ros_A(9) = 0.1253708332932087E+02_dp
    ros_A(10) =- 0.6878860361058950_dp
    ros_A(11) = ros_A(7)
    ros_A(12) = ros_A(8)
    ros_A(13) = ros_A(9)
    ros_A(14) = ros_A(10)
    ros_A(15) = 1.0_dp

    ros_C(1) =- 0.5668800000000000E+01_dp
    ros_C(2) =- 0.2430093356833875E+01_dp
    ros_C(3) =- 0.2063599157091915_dp
    ros_C(4) =- 0.1073529058151375_dp
    ros_C(5) =- 0.9594562251023355E+01_dp
    ros_C(6) =- 0.2047028614809616E+02_dp
    ros_C(7) = 0.7496443313967647E+01_dp
    ros_C(8) =- 0.1024680431464352E+02_dp
    ros_C(9) =- 0.3399990352819905E+02_dp
    ros_C(10) = 0.1170890893206160E+02_dp
    ros_C(11) = 0.8083246795921522E+01_dp
    ros_C(12) =- 0.7981132988064893E+01_dp
    ros_C(13) =- 0.3152159432874371E+02_dp
    ros_C(14) = 0.1631930543123136E+02_dp
    ros_C(15) =- 0.6058818238834054E+01_dp

  !  ~~~> M_i = Coefficients for new step solution
    ros_M(1) = ros_A(7)
    ros_M(2) = ros_A(8)
    ros_M(3) = ros_A(9)
    ros_M(4) = ros_A(10)
    ros_M(5) = 1.0_dp
    ros_M(6) = 1.0_dp

  !  ~~~> E_i  = Coefficients for error estimator
    ros_E(1) = 0.0_dp
    ros_E(2) = 0.0_dp
    ros_E(3) = 0.0_dp
    ros_E(4) = 0.0_dp
    ros_E(5) = 0.0_dp
    ros_E(6) = 1.0_dp

  !  ~~~> Does the stage i require a new function evaluation (ros_NewF(i)=TRUE)
  !     or does it re-use the function evaluation from stage i- 1 (ros_NewF(i)=FALSE)
    ros_NewF(1) = .TRUE.
    ros_NewF(2) = .TRUE.
    ros_NewF(3) = .TRUE.
    ros_NewF(4) = .TRUE.
    ros_NewF(5) = .TRUE.
    ros_NewF(6) = .TRUE.

  !  ~~~> ros_ELO  = estimator of local order -  the minimum between the
  !          main and the embedded scheme orders plus 1
    ros_ELO = 4.0_dp

  END SUBROUTINE Rodas4
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Rang3
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !   STIFFLY- STABLE W METHOD OF ORDER 3, WITH 4 STAGES
  !  
  !   J. RANG and L. ANGERMANN
  !   NEW ROSENBROCK W- METHODS OF ORDER 3
  !   FOR PARTIAL DIFFERENTIAL ALGEBRAIC
  !          EQUATIONS OF INDEX 1                                             
  !   BIT Numerical Mathematics (2005) 45: 761- 787
  !    DOI: 10.1007/s10543- 005- 0035- y
  !   Table 4.1- 4.2
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    IMPLICIT NONE               !bk kkp31

    rosMethod = RG3
  !  ~~~> Name of the method
    ros_Name = 'RANG-3'
  !  ~~~> Number of stages
    ros_S = 4

    ros_A(1) = 5.09052051067020d+00;
    ros_A(2) = 5.09052051067020d+00;
    ros_A(3) = 0.0d0;
    ros_A(4) = 4.97628111010787d+00;
    ros_A(5) = 2.77268164715849d-02;
    ros_A(6) = 2.29428036027904d-01;

    ros_C(1) = - 1.16790812312283d+01;
    ros_C(2) = - 1.64057326467367d+01;
    ros_C(3) = - 2.77268164715850d-01;
    ros_C(4) = - 8.38103960500476d+00;
    ros_C(5) = - 8.48328409199343d-01;
    ros_C(6) =  2.87009860433106d-01;

    ros_M(1) =  5.22582761233094d+00;
    ros_M(2) = - 5.56971148154165d-01;
    ros_M(3) =  3.57979469353645d-01;
    ros_M(4) =  1.72337398521064d+00;

    ros_E(1) = - 5.16845212784040d+00;
    ros_E(2) = - 1.26351942603842d+00;
    ros_E(3) = - 1.11022302462516d-16;
    ros_E(4) =  2.22044604925031d-16;

    ros_Alpha(1) = 0.0d00;
    ros_Alpha(2) = 2.21878746765329d+00;
    ros_Alpha(3) = 2.21878746765329d+00;
    ros_Alpha(4) = 1.55392337535788d+00;

    ros_Gamma(1) =  4.35866521508459d-01;
    ros_Gamma(2) = - 1.78292094614483d+00;
    ros_Gamma(3) = - 2.46541900496934d+00;
    ros_Gamma(4) = - 8.05529997906370d-01;


  !  ~~~> Does the stage i require a new function evaluation (ros_NewF(i)=TRUE)
  !     or does it re-use the function evaluation from stage i- 1 (ros_NewF(i)=FALSE)
    ros_NewF(1) = .TRUE.
    ros_NewF(2) = .TRUE.
    ros_NewF(3) = .TRUE.
    ros_NewF(4) = .TRUE.

  !  ~~~> ros_ELO  = estimator of local order -  the minimum between the
  !          main and the embedded scheme orders plus 1
    ros_ELO = 3.0_dp

  END SUBROUTINE Rang3
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !     End of the set of internal Rosenbrock subroutines
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
END SUBROUTINE Rosenbrock
 
SUBROUTINE FunTemplate( T, Y, Ydot)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !    Template for the ODE function call.
  !    Updates the rate coefficients (and possibly the fixed species) at each call
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  ~~~> Input variables
    IMPLICIT NONE               !bk kkp32

   REAL(kind=dp) :: T, Y(NVAR)
  !  ~~~> Output variables
   REAL(kind=dp) :: Ydot(NVAR)
  !  ~~~> Local variables
   REAL(kind=dp) :: Told

   Told = TIME
   TIME = T
   CALL Update_SUN()
   CALL Update_RCONST()
   CALL Fun( Y, FIX, RCONST, Ydot)
   TIME = Told

END SUBROUTINE FunTemplate
 
SUBROUTINE JacTemplate( T, Y, Jcb)
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !    Template for the ODE Jacobian call.
  !    Updates the rate coefficients (and possibly the fixed species) at each call
  !  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  !  ~~~> Input variables
    IMPLICIT NONE               !bk kkp33
    REAL(kind=dp) :: T, Y(NVAR)
  !  ~~~> Output variables
#ifdef FULL_ALGEBRA    
    REAL(kind=dp) :: JV(LU_NONZERO), Jcb(NVAR,NVAR)
#else
    REAL(kind=dp) :: Jcb(LU_NONZERO)
#endif   
  !  ~~~> Local variables
    REAL(kind=dp) :: Told
#ifdef FULL_ALGEBRA    
    INTEGER :: i, j
#endif   

    Told = TIME
    TIME = T
    CALL Update_SUN()
    CALL Update_RCONST()
#ifdef FULL_ALGEBRA    
    CALL Jac_SP(Y, FIX, RCONST, JV)
    DO j=1,NVAR
      DO i=1,NVAR
         Jcb(i,j) = 0.0_dp
      END DO
    END DO
    DO i=1,LU_NONZERO
       Jcb(LU_IROW(i),LU_ICOL(i))= JV(i)
    END DO
#else
    CALL Jac_SP( Y, FIX, RCONST, Jcb)
#endif   
    TIME = Told

END SUBROUTINE JacTemplate
 
  SUBROUTINE Update_SUN()
        IMPLICIT NONE               !bk kkp34
       ! USE kchem_kpp_Parameters
       ! USE kchem_kpp_Global


    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
     !  PI -  Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour -  (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet))THEN
       Ttmp = (2.0_dp*Tlocal- SunRise-SunSet)/(SunSet- SunRise)     ! bK added _dp
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = - Ttmp*Ttmp
       END IF
       SUN =(1.0_dp +  COS(PI*Ttmp))/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN
 
SUBROUTINE kpp_integrate (time_step_len,Conc,ierrf,xNacc,xNrej,istatus,l_debug,PE) 
                                                                    
  IMPLICIT NONE                                                     
                                                                    
  REAL(dp),INTENT(IN)                   :: time_step_len           
  REAL(dp),INTENT(INOUT),dimension(:,:) :: Conc                    
  INTEGER, INTENT(OUT),OPTIONAL        :: ierrf(:)                
  INTEGER, INTENT(OUT),OPTIONAL        :: xNacc(:)                
  INTEGER, INTENT(OUT),OPTIONAL        :: xNrej(:)                
  INTEGER, INTENT(INOUT),OPTIONAL      :: istatus(:)              
  INTEGER, INTENT(IN),OPTIONAL         :: PE                      
  LOGICAL, INTENT(IN),OPTIONAL         :: l_debug                 
                                                                    
  INTEGER                                :: k   ! loop variable     
  REAL(dp)                               :: dt                      
  integer,dimension(20)                 :: istatus_u               
  integer                                :: ierr_u                  
                                                                    
                                                                    
  if (present (istatus)) istatus = 0                              
                                                                    
  DO k=1,VL_glo,VL_DIM                                              
!    print*,'vals of vl_glo, vl_dim, is, k, are :',VL_glo,VL_DIM,is,k
    is = k                                                          
    ie = min(k+VL_DIM-1,VL_glo)                                     
    vl = ie-is+1                                                    
                                                                    
    C(:) = Conc(is,:)                                             
                                                                    
    CALL update_rconst   ! photo k of NO2 & RCHO to RCONST(1) & RCONST(6)                                           
     dt = time_step_len                                              
                                                                    
    ! integrate from t=0 to t=dt                                    
    CALL integrate(0._dp,dt,icntrl,rcntrl,istatus_u = istatus_u,ierr_u=ierr_u )     !bK
                                                                    
                                                                    
   IF (PRESENT(l_debug) .AND. PRESENT(PE)) THEN                       
      IF (l_debug) CALL error_output(Conc(is,:),ierr_u,PE)           
   ENDIF                                                              
    Conc(is,:) = C(:)                                                 
                                                                    
    ! Return Diagnostic Information                                 
                                                                    
    if(Present(ierrf))    ierrf(is) = IERR_U                      
    if(Present(xNacc))    xNacc(is) = istatus_u(4)                
    if(Present(xNrej))    xNrej(is) = istatus_u(5)                
                                                                    
    if (present (istatus)) then                                   
      istatus(1:8) = istatus(1:8) + istatus_u(1:8)                 
    end if                                                          
                                                                    
  END DO                                                            
 
                                                                    
! Deallocate input arrays                                           
                                                                    
  if (allocated(TEMP))   deallocate(TEMP)   
                                                                    
  data_loaded = .false.                                             
                                                                    
  return                                                            
END SUBROUTINE kpp_integrate                                        
 
  SUBROUTINE fill_TEMP(status,array) 
    IMPLICIT NONE                                   ! bK kkp35 
    integer,intent(OUT)               :: status 
    real (dp),intent(IN),dimension(:) :: array 
 
    status = 0
    if (.not. allocated(TEMP)) & 
       allocate(TEMP(size(array))) 
 
    IF (data_loaded .AND. (VL_glo /= size(array,1))) THEN 
       status = 1 
       RETURN 
    END IF 
 
    VL_glo = size(array,1) 
    TEMP = array 
    data_loaded = .TRUE. 
 
    RETURN
 
  END   SUBROUTINE fill_TEMP

end module kchem_kpp
 
