! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : smog_Initialize.f90
! Time                 : Mon Mar 13 15:58:02 2017
! Working directory    : /pd/home/khan-b/palm/current_version/trunk/KPP_FOR_PALM/kpp/kchem_kpp
! Equation file        : smog.kpp
! Output root filename : smog
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE smog_Initialize

  USE smog_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE smog_Global

  INTEGER :: i
  REAL(kind=dp) :: x

  CFACTOR = 2.686700e+13_dp

  x = (1.0E-8)*CFACTOR
  DO i = 1, NVAR
    VAR(i) = x
  END DO

  x = (1.0E-8)*CFACTOR
  DO i = 1, NFIX
    FIX(i) = x
  END DO

  VAR(3) = (2.0)*CFACTOR
  VAR(8) = (2.0)*CFACTOR
  VAR(10) = (0.5)*CFACTOR
  VAR(11) = (0.1)*CFACTOR
  FIX(1) = (1.3E+4)*CFACTOR
  FIX(2) = (2.0E+5)*CFACTOR
! constant rate coefficients
  RCONST(2) = 2.183e-05
  RCONST(3) = 26.59
  RCONST(4) = 3775
  RCONST(5) = 23410
  RCONST(7) = 12140
  RCONST(8) = 11270
  RCONST(9) = 11270
  RCONST(10) = 16130
  RCONST(11) = 6893
  RCONST(12) = 0.02143
! END constant rate coefficients

! INLINED initializations

	TSTART = 0
	TEND = TSTART + 600
	DT = 60.0
        TEMP = 298

! End INLINED initializations

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE smog_Initialize

