! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : smog_Monitor.f90
! Time                 : Mon Mar 13 15:58:02 2017
! Working directory    : /pd/home/khan-b/palm/current_version/trunk/KPP_FOR_PALM/kpp/kchem_kpp
! Equation file        : smog.kpp
! Output root filename : smog
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE smog_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(16) :: SPC_NAMES = (/ &
     'HNO3           ','O              ','RH             ', &
     'RCOO2NO2       ','O3             ','HO2            ', &
     'RCOO2          ','RCHO           ','RO2            ', &
     'NO             ','NO2            ','OH             ', &
     'H2O            ','O2             ','CO             ', &
     'CO2            ' /)

  INTEGER, PARAMETER, DIMENSION(16) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, &
      13, 14, 15, 16 /)

  INTEGER, PARAMETER, DIMENSION(1) :: MONITOR = (/ &
       5 /)

  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(12) :: EQN_NAMES = (/ &
     '        NO2 --> O + NO                                                                              ', &
     '     O + O2 --> O3                                                                                  ', &
     '    O3 + NO --> NO2 + O2                                                                            ', &
     '    RH + OH --> RO2 + H2O                                                                           ', &
     '  RCHO + OH --> RCOO2 + H2O                                                                         ', &
     '       RCHO --> HO2 + RO2 + CO                                                                      ', &
     '   HO2 + NO --> NO2 + OH                                                                            ', &
     '   RO2 + NO --> HO2 + RCHO + NO2                                                                    ', &
     ' RCOO2 + NO --> RO2 + NO2 + CO2                                                                     ', &
     '   NO2 + OH --> HNO3                                                                                ', &
     'RCOO2 + NO2 --> RCOO2NO2                                                                            ', &
     '   RCOO2NO2 --> RCOO2 + NO2                                                                         ' /)

! INLINED global variables

! End INLINED global variables


END MODULE smog_Monitor
