! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : smog_Parameters.f90
! Time                 : Mon Mar 13 15:58:02 2017
! Working directory    : /pd/home/khan-b/palm/current_version/trunk/KPP_FOR_PALM/kpp/kchem_kpp
! Equation file        : smog.kpp
! Output root filename : smog
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE smog_Parameters

  USE smog_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 16 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 12 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 11 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 4 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 12 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 13 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 53 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 59 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 13 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 13 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 28 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 16 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_HNO3 = 1 
  INTEGER, PARAMETER :: ind_O = 2 
  INTEGER, PARAMETER :: ind_RH = 3 
  INTEGER, PARAMETER :: ind_RCOO2NO2 = 4 
  INTEGER, PARAMETER :: ind_O3 = 5 
  INTEGER, PARAMETER :: ind_HO2 = 6 
  INTEGER, PARAMETER :: ind_RCOO2 = 7 
  INTEGER, PARAMETER :: ind_RCHO = 8 
  INTEGER, PARAMETER :: ind_RO2 = 9 
  INTEGER, PARAMETER :: ind_NO = 10 
  INTEGER, PARAMETER :: ind_NO2 = 11 
  INTEGER, PARAMETER :: ind_OH = 12 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 13 
  INTEGER, PARAMETER :: ind_O2 = 14 
  INTEGER, PARAMETER :: ind_CO = 15 
  INTEGER, PARAMETER :: ind_CO2 = 16 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_O2 = 2 
  INTEGER, PARAMETER :: indf_CO = 3 
  INTEGER, PARAMETER :: indf_CO2 = 4 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 20 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 39 

END MODULE smog_Parameters

