! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : smog_HessianSP.f90
! Time                 : Mon Mar 13 15:58:02 2017
! Working directory    : /pd/home/khan-b/palm/current_version/trunk/KPP_FOR_PALM/kpp/kchem_kpp
! Equation file        : smog.kpp
! Output root filename : smog
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE smog_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(28) :: IHESS_I = (/ &
       1,  3,  4,  5,  6,  6,  7,  7,  7,  8,  8,  9, &
       9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, &
      12, 12, 12, 12 /)

  INTEGER, PARAMETER, DIMENSION(28) :: IHESS_J = (/ &
      11,  3,  7,  5,  6,  9,  7,  7,  8,  8,  9,  3, &
       7,  9,  5,  6,  7,  9,  5,  6,  7,  7,  9, 11, &
       3,  6,  8, 11 /)

  INTEGER, PARAMETER, DIMENSION(28) :: IHESS_K = (/ &
      12, 12, 11, 10, 10, 10, 10, 11, 12, 12, 10, 12, &
      10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 10, 12, &
      12, 10, 12, 12 /)


END MODULE smog_HessianSP

