! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : smog_Jacobian.f90
! Time                 : Mon Mar 13 15:58:02 2017
! Working directory    : /pd/home/khan-b/palm/current_version/trunk/KPP_FOR_PALM/kpp/kchem_kpp
! Equation file        : smog.kpp
! Output root filename : smog
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE smog_Jacobian

  USE smog_Parameters
  USE smog_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(21)

! B(1) = dA(1)/dV(11)
  B(1) = RCT(1)
! B(2) = dA(2)/dV(2)
  B(2) = 2.183e-05*F(2)
! B(4) = dA(3)/dV(5)
  B(4) = 26.59*V(10)
! B(5) = dA(3)/dV(10)
  B(5) = 26.59*V(5)
! B(6) = dA(4)/dV(3)
  B(6) = 3775*V(12)
! B(7) = dA(4)/dV(12)
  B(7) = 3775*V(3)
! B(8) = dA(5)/dV(8)
  B(8) = 23410*V(12)
! B(9) = dA(5)/dV(12)
  B(9) = 23410*V(8)
! B(10) = dA(6)/dV(8)
  B(10) = RCT(6)
! B(11) = dA(7)/dV(6)
  B(11) = 12140*V(10)
! B(12) = dA(7)/dV(10)
  B(12) = 12140*V(6)
! B(13) = dA(8)/dV(9)
  B(13) = 11270*V(10)
! B(14) = dA(8)/dV(10)
  B(14) = 11270*V(9)
! B(15) = dA(9)/dV(7)
  B(15) = 11270*V(10)
! B(16) = dA(9)/dV(10)
  B(16) = 11270*V(7)
! B(17) = dA(10)/dV(11)
  B(17) = 16130*V(12)
! B(18) = dA(10)/dV(12)
  B(18) = 16130*V(11)
! B(19) = dA(11)/dV(7)
  B(19) = 6893*V(11)
! B(20) = dA(11)/dV(11)
  B(20) = 6893*V(7)
! B(21) = dA(12)/dV(4)
  B(21) = 0.02143

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,11)
  JVS(2) = B(17)
! JVS(3) = Jac_FULL(1,12)
  JVS(3) = B(18)
! JVS(4) = Jac_FULL(2,2)
  JVS(4) = -B(2)
! JVS(5) = Jac_FULL(2,11)
  JVS(5) = B(1)
! JVS(6) = Jac_FULL(3,3)
  JVS(6) = -B(6)
! JVS(7) = Jac_FULL(3,12)
  JVS(7) = -B(7)
! JVS(8) = Jac_FULL(4,4)
  JVS(8) = -B(21)
! JVS(9) = Jac_FULL(4,7)
  JVS(9) = B(19)
! JVS(10) = Jac_FULL(4,11)
  JVS(10) = B(20)
! JVS(11) = Jac_FULL(5,2)
  JVS(11) = B(2)
! JVS(12) = Jac_FULL(5,5)
  JVS(12) = -B(4)
! JVS(13) = Jac_FULL(5,10)
  JVS(13) = -B(5)
! JVS(14) = Jac_FULL(5,11)
  JVS(14) = 0
! JVS(15) = Jac_FULL(6,6)
  JVS(15) = -B(11)
! JVS(16) = Jac_FULL(6,8)
  JVS(16) = B(10)
! JVS(17) = Jac_FULL(6,9)
  JVS(17) = B(13)
! JVS(18) = Jac_FULL(6,10)
  JVS(18) = -B(12)+B(14)
! JVS(19) = Jac_FULL(7,4)
  JVS(19) = B(21)
! JVS(20) = Jac_FULL(7,7)
  JVS(20) = -B(15)-B(19)
! JVS(21) = Jac_FULL(7,8)
  JVS(21) = B(8)
! JVS(22) = Jac_FULL(7,10)
  JVS(22) = -B(16)
! JVS(23) = Jac_FULL(7,11)
  JVS(23) = -B(20)
! JVS(24) = Jac_FULL(7,12)
  JVS(24) = B(9)
! JVS(25) = Jac_FULL(8,8)
  JVS(25) = -B(8)-B(10)
! JVS(26) = Jac_FULL(8,9)
  JVS(26) = B(13)
! JVS(27) = Jac_FULL(8,10)
  JVS(27) = B(14)
! JVS(28) = Jac_FULL(8,12)
  JVS(28) = -B(9)
! JVS(29) = Jac_FULL(9,3)
  JVS(29) = B(6)
! JVS(30) = Jac_FULL(9,7)
  JVS(30) = B(15)
! JVS(31) = Jac_FULL(9,8)
  JVS(31) = B(10)
! JVS(32) = Jac_FULL(9,9)
  JVS(32) = -B(13)
! JVS(33) = Jac_FULL(9,10)
  JVS(33) = -B(14)+B(16)
! JVS(34) = Jac_FULL(9,11)
  JVS(34) = 0
! JVS(35) = Jac_FULL(9,12)
  JVS(35) = B(7)
! JVS(36) = Jac_FULL(10,5)
  JVS(36) = -B(4)
! JVS(37) = Jac_FULL(10,6)
  JVS(37) = -B(11)
! JVS(38) = Jac_FULL(10,7)
  JVS(38) = -B(15)
! JVS(39) = Jac_FULL(10,8)
  JVS(39) = 0
! JVS(40) = Jac_FULL(10,9)
  JVS(40) = -B(13)
! JVS(41) = Jac_FULL(10,10)
  JVS(41) = -B(5)-B(12)-B(14)-B(16)
! JVS(42) = Jac_FULL(10,11)
  JVS(42) = B(1)
! JVS(43) = Jac_FULL(10,12)
  JVS(43) = 0
! JVS(44) = Jac_FULL(11,4)
  JVS(44) = B(21)
! JVS(45) = Jac_FULL(11,5)
  JVS(45) = B(4)
! JVS(46) = Jac_FULL(11,6)
  JVS(46) = B(11)
! JVS(47) = Jac_FULL(11,7)
  JVS(47) = B(15)-B(19)
! JVS(48) = Jac_FULL(11,8)
  JVS(48) = 0
! JVS(49) = Jac_FULL(11,9)
  JVS(49) = B(13)
! JVS(50) = Jac_FULL(11,10)
  JVS(50) = B(5)+B(12)+B(14)+B(16)
! JVS(51) = Jac_FULL(11,11)
  JVS(51) = -B(1)-B(17)-B(20)
! JVS(52) = Jac_FULL(11,12)
  JVS(52) = -B(18)
! JVS(53) = Jac_FULL(12,3)
  JVS(53) = -B(6)
! JVS(54) = Jac_FULL(12,6)
  JVS(54) = B(11)
! JVS(55) = Jac_FULL(12,8)
  JVS(55) = -B(8)
! JVS(56) = Jac_FULL(12,9)
  JVS(56) = 0
! JVS(57) = Jac_FULL(12,10)
  JVS(57) = B(12)
! JVS(58) = Jac_FULL(12,11)
  JVS(58) = -B(17)
! JVS(59) = Jac_FULL(12,12)
  JVS(59) = -B(7)-B(9)-B(18)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(11)+JVS(3)*UV(12)
  JUV(2) = JVS(4)*UV(2)+JVS(5)*UV(11)
  JUV(3) = JVS(6)*UV(3)+JVS(7)*UV(12)
  JUV(4) = JVS(8)*UV(4)+JVS(9)*UV(7)+JVS(10)*UV(11)
  JUV(5) = JVS(11)*UV(2)+JVS(12)*UV(5)+JVS(13)*UV(10)
  JUV(6) = JVS(15)*UV(6)+JVS(16)*UV(8)+JVS(17)*UV(9)+JVS(18)*UV(10)
  JUV(7) = JVS(19)*UV(4)+JVS(20)*UV(7)+JVS(21)*UV(8)+JVS(22)*UV(10)+JVS(23)*UV(11)+JVS(24)*UV(12)
  JUV(8) = JVS(25)*UV(8)+JVS(26)*UV(9)+JVS(27)*UV(10)+JVS(28)*UV(12)
  JUV(9) = JVS(29)*UV(3)+JVS(30)*UV(7)+JVS(31)*UV(8)+JVS(32)*UV(9)+JVS(33)*UV(10)+JVS(35)*UV(12)
  JUV(10) = JVS(36)*UV(5)+JVS(37)*UV(6)+JVS(38)*UV(7)+JVS(40)*UV(9)+JVS(41)*UV(10)+JVS(42)*UV(11)
  JUV(11) = JVS(44)*UV(4)+JVS(45)*UV(5)+JVS(46)*UV(6)+JVS(47)*UV(7)+JVS(49)*UV(9)+JVS(50)*UV(10)+JVS(51)*UV(11)+JVS(52)&
              &*UV(12)
  JUV(12) = JVS(53)*UV(3)+JVS(54)*UV(6)+JVS(55)*UV(8)+JVS(57)*UV(10)+JVS(58)*UV(11)+JVS(59)*UV(12)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(4)*UV(2)+JVS(11)*UV(5)
  JTUV(3) = JVS(6)*UV(3)+JVS(29)*UV(9)+JVS(53)*UV(12)
  JTUV(4) = JVS(8)*UV(4)+JVS(19)*UV(7)+JVS(44)*UV(11)
  JTUV(5) = JVS(12)*UV(5)+JVS(36)*UV(10)+JVS(45)*UV(11)
  JTUV(6) = JVS(15)*UV(6)+JVS(37)*UV(10)+JVS(46)*UV(11)+JVS(54)*UV(12)
  JTUV(7) = JVS(9)*UV(4)+JVS(20)*UV(7)+JVS(30)*UV(9)+JVS(38)*UV(10)+JVS(47)*UV(11)
  JTUV(8) = JVS(16)*UV(6)+JVS(21)*UV(7)+JVS(25)*UV(8)+JVS(31)*UV(9)+JVS(55)*UV(12)
  JTUV(9) = JVS(17)*UV(6)+JVS(26)*UV(8)+JVS(32)*UV(9)+JVS(40)*UV(10)+JVS(49)*UV(11)
  JTUV(10) = JVS(13)*UV(5)+JVS(18)*UV(6)+JVS(22)*UV(7)+JVS(27)*UV(8)+JVS(33)*UV(9)+JVS(41)*UV(10)+JVS(50)*UV(11)+JVS(57)&
               &*UV(12)
  JTUV(11) = JVS(2)*UV(1)+JVS(5)*UV(2)+JVS(10)*UV(4)+JVS(23)*UV(7)+JVS(42)*UV(10)+JVS(51)*UV(11)+JVS(58)*UV(12)
  JTUV(12) = JVS(3)*UV(1)+JVS(7)*UV(3)+JVS(24)*UV(7)+JVS(28)*UV(8)+JVS(35)*UV(9)+JVS(52)*UV(11)+JVS(59)*UV(12)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE smog_Jacobian

