! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : smog_StoichiomSP.f90
! Time                 : Mon Mar 13 15:58:02 2017
! Working directory    : /pd/home/khan-b/palm/current_version/trunk/KPP_FOR_PALM/kpp/kchem_kpp
! Equation file        : smog.kpp
! Output root filename : smog
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE smog_StoichiomSP

  USE smog_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(13) :: CROW_JVRP = (/ &
       1,  2,  3,  5,  7,  9, 10, 12, 14, 16, 18, 20, &
      21 /)

  INTEGER, PARAMETER, DIMENSION(20) :: ICOL_JVRP = (/ &
      11,  2,  5, 10,  3, 12,  8, 12,  8,  6, 10,  9, &
      10,  7, 10, 11, 12,  7, 11,  4 /)

  INTEGER, PARAMETER, DIMENSION(20) :: IROW_JVRP = (/ &
       1,  2,  3,  3,  4,  4,  5,  5,  6,  7,  7,  8, &
       8,  9,  9, 10, 10, 11, 11, 12 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(13) :: CCOL_STOICM = (/ &
       1,  4,  6,  9, 12, 15, 18, 22, 27, 31, 34, 37, &
      40 /)

  INTEGER, PARAMETER, DIMENSION(39) :: IROW_STOICM = (/ &
       2, 10, 11,  2,  5,  5, 10, 11,  3,  9, 12,  7, &
       8, 12,  6,  8,  9,  6, 10, 11, 12,  6,  8,  9, &
      10, 11,  7,  9, 10, 11,  1, 11, 12,  4,  7, 11, &
       4,  7, 11 /)

  INTEGER, PARAMETER, DIMENSION(39) :: ICOL_STOICM = (/ &
       1,  1,  1,  2,  2,  3,  3,  3,  4,  4,  4,  5, &
       5,  5,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8, &
       8,  8,  9,  9,  9,  9, 10, 10, 10, 11, 11, 11, &
      12, 12, 12 /)

  REAL(kind=dp), PARAMETER, DIMENSION(39) :: STOICM = (/ &
       1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, &
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp /)


END MODULE smog_StoichiomSP

